= Stacks


A _stack_ is a collection that implements the last-in-first-out (LIFO) protocol. This means that the only accessible object in the collection is the last one that was inserted. A stack of books is a good analogy: You can’t take a book from the stack without first removing the books that are stacked on top of it.

== STACK OPERATIONS

The fundamental operations of a stack are:

 . Add an element onto the top of the stack.
 . Access the current element on the top of the stack.
 . Remove the current element on the top of the stack. These three operations are usually named push, peek, and pop, respectively.

== THE JCF Stack CLASS

As shown in Figure 4.1 on page 70, the Java Collections Framework includes a Vector class, which is a specialized List type. Prior to the development of the JCF, Java extended the Vector class to a Stack class. But that class is now considered obsolete because it isn’t consistent with the JCF. Instead, the Java API recommends using the ArrayDeque class for stacks, like this:

[source,java]
----
Deque<String> stack = new ArrayDeque<String>();
----
This provides all the normal functionality of a stack, while being consistent with the JCF. (See page 91.)

=== EXAMPLE 5.1 Testing a String Stack

[source,java]
----
1	public class TestStringStack {
2	public static void main(String[] args) {
3	Deque<String> stack = new ArrayDeque<String>();
4	stack.push("GB");
5	stack.push("DE");
6	stack.push("FR");
7	stack.push("ES");
8	System.out.println(stack);
9	System.out.println("stack.peek(): " + stack.peek());
10		System.out.println("stack.pop(): " + stack.pop());
11		System.out.println(stack);
12		System.out.println("stack.pop(): " + stack.pop());
13		System.out.println(stack);
14		System.out.println("stack.push(\"IE\"): ");
15		stack.push("IE");
16		System.out.println(stack);
17	}
18	}
----

The output is:

[source,console]
----
[ES, FR, DE, GB]
stack.peek(): ES
stack.pop(): ES
[FR, DE, GB]
stack.pop(): FR
[DE, GB]
stack.push("IE"):
[IE, DE, GB]
----
The push, peek, and pop operations are illustrated at lines 4, 9, and 10, respectively.

== A Stack INTERFACE

The operational requirements of a stack (peek, pop, and push) can be formalized as a Java interface:

=== EXAMPLE 5.2 A Stack Interface

[source,java]
----
1	public interface Stack<E> {
2	public boolean isEmpty();
3	public E peek();
4	public E pop();
5	public void push(E element);
6	public int size();
7	}
----

The symbol E is a type parameter. (See page 76.) It stands for the deferred element type for the stack.

In addition to the three required stack operations, this interface also specifies an isEmpty() method and a size() method.

The Stack interface shown in Example 5.2 is a generic type. (See page 76.) The expression <E> at line 1 means that the element type E is unspecified.

== AN INDEXED IMPLEMENTATION

There are several ways to implement the Stack interface. The simplest is an indexed implementation, using an ordinary array.

=== EXAMPLE 5.3 An ArrayStack Implementation

[source,java]
----
1	public class ArrayStack<E> implements Stack<E> {
2	    private E[] elements;
3	    private int size;
4	    private static final int INITIAL_CAPACITY = 100;
5
6		public ArrayStack() {
7		    elements = (E[]) new Object[INITIAL_CAPACITY];
8		}
9
10		public ArrayStack(int capacity) {
11		    elements = (E[]) new Object[capacity];
12		}
13
14		public boolean isEmpty() {
15		    return (size == 0);
16		}
17
18		public E peek() {
19		    if (size == 0) {
20		        throw new java.util.EmptyStackException();
21		    }
22		    return elements[size-1]; // top of stack
23		}
24
25		public E pop() {
26		    if (size == 0) {
27		        throw new java.util.EmptyStackException();
28		    }
29		    E element = elements[--size];
30		    elements[size] = null;
31		    return element;
32		}
33
34		public void push(E element) {
35		    if (size == elements.length) {
36		        resize();
37		    }
38		    elements[size++] = element;
39		}
40
41		public int size() {
42		    return size;
43		}
44
45		private void resize() {
46		    assert size == elements.length;
47		    Object[] a = new Object[2*size];
48		    System.arraycopy(elements, 0, a, 0, size);
49		    elements = (E[])a;
50		}
51	}
----

Since this class is implementing the generic type Stack<E>, it too is a generic type. Thus, the type parameter E is used wherever the element type has to be specified. For example, at line 29, the local variable element is declared to have type E.

This ArrayStack implementation uses a “backing array” elements[] to store the stack’s elements. It is declared at line 2 to have type E[], that is, an array of elements of type E. The other class field is the integer size, which keeps a count of the number of elements in the stack.

The class defines the static constant INITIAL_CAPACITY at line 4 to be the number 100. This is used only to specify the initial size of the backing array at line 7. The choice of 100 is arbitrary; any reasonably small positive integer would suffice.

Two constructors are defined: the default (no-argument) constructor at line 6 and the one-argument constructor at line 10. Both merely allocate the backing array, using either the default INITIAL_CAPACITY (line 7) or a user-specified capacity (line 11).
Notice how arrays are allocated in a generic collection:

[source,java]
----
7	elements = (E[]) new Object[INITIAL_CAPACITY];
----
Since generic arrays are not supported in Java, this simpler approach

[source,java]
----
elements = new E[INITIAL_CAPACITY];	// ERROR!
----

will not compile. Instead, we have to allocate the backing array as an array of Object elements, and then cast that array with (E[]) in order to assign it to the elements field, which has type E[]. This subterfuge may generate a compiler warning, which can be ignored.

The implementations of the five methods required by the Stack interface are pretty straightforward. The size() method at line 41 is an accessor method that simply returns the value of the size field. The isEmpty() method at line 14 returns true or false according to whether or not the value of size is 0.

The peek() method at line 18 throws an exception if the stack is empty. Otherwise, it returns the top element on the stack: elements[size-1].

The pop() method at line 25 is almost the same as the peek() method. But before returning the top element, it must remove it by decrementing the size field at line 29 and replacing the top element with null at line 30. This last step is done so that no references will be left to an inaccessible object.

The push() method at line 34 is essentially the reverse of the pop() method. At line 38, the element is added to the array at the next available position, at elements[size], and then the size counter is post- decremented.

If the array is full, then the size counter will equal elements.length. If that condition holds when push() is called, the array is doubled by a call to the private resize() method at line 36. This creates the temporary array a[] at line 47, copies all the elements into it at line 48, and then assigns the elements field to it at line 49.

Note the use of the assert statement at line 46. If the condition size == elements.length does not hold at that point, the program will abort with an error message, just like an uncaught exception. Of course, that should never happen, because the resize() method is private, and the only place where it is called within this class is at line 36, inside the if block for that same condition. The purpose of including the assert statement here is merely “insurance,” to guard against possible future modifications of the class that might inadvertently involve the resize() method when that condition is not true.

The ArrayStack class implemented in Example 5.3 can be tested the same way the Stack class is tested in Example 5.1 on page 103. The push(), peek(), and pop() calls should work the same way. The println() calls cannot be executed for the ArrayStack class because it has no toString() method. But that’s proper, because a stack really should not allow access to any of its elements other than the one on top.

== A LINKED IMPLEMENTATION

The main alternative to an indexed implementation is a linked implementation, using a linked list. (See Chapter 3.)

=== EXAMPLE 5.4 A LinkedStack Implementation

[source,java]
----
1	public class LinkedStack<E> implements Stack<E> {
2	    private Node<E> head = new Node<E>(); // dummy node
3	    private int size;
4
5	    public boolean isEmpty() {
6	        return (size == 0);
7	    }
8
9	    public E peek() {
10	        if (size == 0) {
11	            throw new java.util.EmptyStackException();
12	        }
13	        return head.prev.element; // top of stack
14	    }
15
16	    public E pop() {
17	        if (size == 0) {
18	            throw new java.util.EmptyStackException();
19	        }
20	        E element = head.prev.element;
21	        head.prev = head.prev.prev;
22	        head.prev.next = head;
23	        --size;
24	        return element;
25	    }
26
27	    public void push(E element) {
28	        head.prev = head.prev.next = new Node<E>(element, head.prev, head);
29	        ++size;
30	    }
31
32	    public int size() {
33	        return size;
34	    }
35
36	    private static class Node<E> {
37	        E element;
38	        Node<E> prev;
39	        Node<E> next;
40
41	        Node() {
42	            this.prev = this.next = this;
43	        }
44
45	        Node(E element, Node<E> prev, Node<E> next) {
46	            this.element = element;
47	            this.prev = prev;
48	            this.next = next;
49	        }
50	    }
51	}
----

This class implements a doubly linked list, using the private inner Node class defined at lines 36–50. Each node contains an element field and two link fields: one pointed to the previous node in the list and one pointing to the next node. The constructor defined at line 41 constructs a dummy node with null element and with both links pointing to the node itself. The three-argument constructor defined at line 45 allows all three fields to be initialized.

The LinkedStack class defines two fields at lines 2–3: its head node link and its size counter. Note that this implements the empty stack as a single dummy node with its prev and next links pointing to the node itself. The advantage of self-pointers is that we avoid null pointers, obviating special cases in the push() and pop() methods.

When the stack is not empty, the top element will always be in the node referenced by the head.prev link. Thus, both peek() and pop() return head.prev.element.

To remove the top element, pop() deletes the node that contains it. This requires resetting two pointers, which is done at lines 21-22:

[source,java]
----
21	head.prev = head.prev.prev;
22	head.prev.prev.next = head;
----

The push() method constructs a new node containing the specified element at line 28, and then it resets both the head.prev.next and the head.prev links to point to it. Note that the chained assignment works from right to left, first assigning the new node reference to head.prev.next and then to head.prev. That order of operations is critical because the existing head.prev.next node is not accessible after head.prev is changed.

== ABSTRACTING THE COMMON CODE

The ArrayStack and LinkedStack implementations of the Stack interface are quite different. Nevertheless, they do have some identical code. The size() method and the isEmpty() method are the same. Their implementation does not depend upon whether the backing structure is indexed or linked.

When parts of an implementation are independent of the underlying data structure, it is advantageous to implement those parts separately in an abstract class.

=== EXAMPLE 5.5 An AbstractStack Class

[source,java]
----
1	public abstract class AbstractStack<E> implements Stack<E> {
2	    protected int size;
3
4	    public boolean isEmpty() {
5	        return (size == 0);
6	    }
7
8	    abstract public E peek();
9
10	    abstract public E pop();
11
12	    abstract public void push(E element);
13
14	    public int size() {
15	        return size;
16	    }
17	}
----

The three methods that depend upon the implementation’s backing structure are declared abstract (lines 8, 10, and 12). This of course requires the class itself to be declared abstract.

Notice at line 2 that the size field is declared protected instead of private so that it can be accessed by the extending concrete classes.

With the AbstractStack class implemented as shown in Example 5.5, we can now simplify the two concrete implementations from Example 5.3 on page 104 and Example 5.4 on page 106. We need only add the expression extends AbstractStack<E> to each class header, and then we can remove their isEmpty() and size() methods and their declaration of the size field. This of course is the strategy used by the JCF. (See Figure 4.1 on page 70.)

== APPLICATION: AN RPN CALCULATOR

Although the stack data structure is one of the simplest, it is essential in certain important applications. Some of these are illustrated in the following examples.

An arithmetic expression is said to be in _postfix_ notation (also called reverse _Polish notation_, or RPN) if each operator is placed after its operands. For example, the postfix expression for 3\*(4 + 5) is 3 4 5 + *. [The expression 3*(4 + 5) is called an _infix expression_.] Postfix expressions are easier to process by machine than are infix expressions. Calculators that process postfix expressions are called _RPN calculators_.

=== EXAMPLE 5.6 An RPN Calculator

This program parses postfix expressions, performing the indicated arithmetic. It uses a stack to accumulate the operands.

[source,java]
----
1	public class Calculator {
2	    public static void main(String[] args) {
3	        Deque<String> stack = new ArrayDeque<String>();
4	        Scanner in = new Scanner(System.in);
5	        while (true) {
6	            String input = in.nextLine();
7	            char ch = input.charAt(0);
8	            if (ch == '+' || ch == '-' || ch == '*' || ch == '/') {
9	                double y = Double.parseDouble(stack.pop());
10	                double x = Double.parseDouble(stack.pop());
11	                double z = 0;
12	                switch	(ch)	{
13	                    case	'+':	z = x +	y; break;
14	                    case	'-':	z = x -	y; break;
15	                    case	'*':	z = x *	y; break;
16	                    case	'/':	z = x /	y;
17	                }
18	                System.out.printf("\t%.2f %c %.2f = %.2f%n", x, ch, y, z);
19	                stack.push(new Double(z).toString());
20	            } else if (ch == 'q' || ch == 'Q') {
21	                return;
22	            } else {
23	                stack.push(input);
24	            }
25	        }
26	    }
27	}
----

Here is one run:

[source,console]
----
3
4
5
+
4.00 + 5.00 = 9.00
*
3.00 * 9.00 = 27.00
10
/
27.00 / 10.00 = 2.70
1 –
2.70 – 1.00 = 1.70
Q
----


At line 3, the program instantiates a stack of strings, like the one in Example 5.1 on page 103. Then it goes into an infinite while loop at line 5, interactively reading a string on each iteration at line 6.

If the user inputs anything other than +, -, *, /, q, or Q, the program assumes it is a number and pushes it onto the stack at line 23. If it is one of the four arithmetic operations, then the top two numbers are popped off the stack at lines 9–10 and the operation is applied to them. The result is printed at line 18 and then pushed onto the stack at line 19.

The program ends when the user enters q or Q (for “quit”).

Human readers tend to prefer infix to postfix notation for arithmetic expressions. The following example converts a given infix expression to postfix.

=== EXAMPLE 5.7 Converting Infix to Postfix

[source,java]
----
1	public class TestScanner {
2	    public static void main(String[] args) {
3	        Deque<String> stack = new ArrayDeque<String>();
4	        String line = new Scanner(System.in).nextLine();
5	        System.out.println(line);
6	        Scanner scanner = new Scanner(line);
7	        while (scanner.hasNext()) {
8	            if (scanner.hasNextInt()) {
9	                System.out.print(scanner.nextInt() + " ");
10	            } else {
11	                String str = scanner. next();
12	                if ("+-*/".indexOf(str) >= 0) {
13	                    stack.push(str);
14	                } else if (str.equals(")")) {
15	                    System.out.print(stack.pop() + " ");
16	                }
17	            }
18	        }
19	        while (!stack.isEmpty()) {
20	            System.out.print(stack.pop() + " ");
21	        }
22	        System.out.println();
23	    }
24	}
----

The output is:

[source,java]
----
( 80 - 30 ) * ( 40 + 50 / 10 )
80 30 - 40 50 10 / + *
----

The output shows that the program parsed the infix expression ( 80 - 30 )*( 40 + 50 / 10 ) to generate its postfix equivalent 80 30 - 40 50 10 / + *.

The program uses a stack, declared at line 3, and a scanner, declared at line 6. The scanner extracts integer and string tokens from the input line. If the token is an integer, it is printed immediately, at line 9. If it is one of the four strings "+", "-", "*", or "/", it is pushed onto the stack at line 13. If it is the strings ")", then the top element of the stack is popped off and printed at line 15. After the input line has been completely parsed, the remaining elements are popped from the stack and printed at lines 19-21.

== Review Questions

1. Why are stacks called LIFO structures?
2. Would it make sense to call a stack
a. a LILO structure?
b. a FILO structure?
3. What is
a. xprefix notation?
b. infix notation?
c. postfix notation?
4. Determine whether each of the following is true about postfix expressions:
a. x y + z + = x y z + +
b. x y + z - = x y z - +
c. x y - z + = x y z + -
d. x y - z - = x y z - -

== Problems

1. Trace the following code, showing the contents of the stack after each invocation:
+
[source,java]
----
Stack stack = new Stack();
stack.push(new Character('A'));
stack.push(new Character('B'));
stack.push(new Character('C'));
stack.pop();
stack.pop();
stack.push(new Character('D'));
stack.push(new Character('E'));
stack.push(new Character('F'));
stack.pop();
stack.push(new Character('G'));
stack.pop();
stack.pop();
stack.pop();
----
2. Translate each of the following prefix expressions into infix:
a. - / + * a b c d e
b. / - a b * c + d e
c. / a + b * c - d e
3. Translate the prefix expressions in Problem 5.2 into postfix.
4. Translate each of the following infix expressions into prefix:
a. ( a + b ) - ( c / ( d + e ) )
b. a / ( ( b / c ) * ( d - e ) )
c. ( a / ( b / c ) ) * ( d - e )
5. Translate the infix expressions in Problem 5.4 into postfix.
6. Translate each of the following postfix expressions into prefix:
a. a b + c d - / e +
b. a b c + d e - * -
c. a b c d e / / / /
7. Translate the postfix expressions in Problem 5.6 into infix.
8. Write this client method using only the push(), peek(), pop(), and isEmpty() methods:
+
[source,java]
----
public static <E> Deque<E> reversed(Deque<E> stack)
// returns a new stack that contains the same elements as the given
// stack, but in reversed order
----
9. Write this client method using only the push(), peek(), pop(), and isEmpty() methods:
+
[source,java]
----
public static <E> Deque<E> reversed(Deque<E> stack)
// returns a new stack that contains the same elements as the given
// stack, but in reversed order, and leaves the given stack in its
// original state
----
10. Write this client method using only the push(), peek(), pop(), and isEmpty() methods:
+
[source,java]
----
public static <E> void reverse(Deque<E> stack)
// reverses the contents of the specified stack
----
11. Write this client method using only the push(), peek(), pop(), and isEmpty() methods:
+
[source,java]
----
public static <E> E penultimate(Deque<E> stack)
// returns the second from the top element of the specified stack
----
12. Write this client method using only the push(), peek(), pop(), and isEmpty() methods:
+
[source,java]
----
public static <E> E popPenultimate(Deque<E> stack)
// removes and returns the second element of the specified stack
----
13. Write this client method using only the push(), peek(), pop(), and isEmpty() methods:
+
[source,java]
----
public static <E> E bottom(Deque<E> stack)
// returns the bottom element of the specified stack
----
14. Write this client method using only the push(), peek(), pop(), and isEmpty() methods:
+
[source,java]
----
public static <E> E popBottom(Deque<E> stack)
// removes and returns the bottom element of the specified stack
----
15. Add this member method to the ArrayStack class shown in Example 5.3 on page 104:
+
[source,java]
----
public void reverse()
// reverses the contents of this stack
----
16. Add this member method to the LinkedStack class shown in Example 5.4 on page 106:
+
[source,java]
----
public void reverse()
// reverses the contents of this stack
----
17. Add this member method to the ArrayStack class shown in Example 5.3 on page 104:
+
[source,java]
----
public E penultimate()
// returns the second from the top element of this stack
----
18. Add this member method to the LinkedStack class shown in Example 5.4 on page 106:
+
[source,java]
----
public E penultimate()
// returns the second from the top element of this stack
----
19. Add this member method to the ArrayStack class shown in Example 5.3 on page 104:
+
[source,java]
----
public E popPenultimate()
// removes and returns the second element of this stack
----
20. Add this member method to the LinkedStack class shown in Example 5.4 on page 106:
+
[source,java]
----
public E popPenultimate()
// removes and returns the second element of this stack
----
21. Add this member method to the ArrayStack class shown in Example 5.3 on page 104:
+
[source,java]
----
public E bottom()
// returns the bottom element of this stack
----
22. Add this member method to the LinkedStack class shown in Example 5.4 on page 106:
+
[source,java]
----
public E bottom()
// returns the bottom element of this stack
----
23. Add this member method to the ArrayStack class shown in Example 5.3 on page 104:
+
[source,java]
----
public E popBottom()
// removes and returns the bottom element of this stack
----
24. Add this member method to the LinkedStack class shown in Example 5.4 on page 106:
+
[source,java]
----
public E popBottom()
// removes and returns the bottom element of this stack
----
