:stem: latexmath

= Queues

A queue is a collection that implements the first-in-first-out (FIFO) protocol. This means that the only accessible object in the collection is the first one that was inserted. The most common example of a queue is a waiting line.

== QUEUE OPERATIONS

The fundamental operations of a queue are:

1.	Add an element to the back of the queue.
2.	Access the current element at the front of the queue.
3.	Remove the current element at the front of the queue.

Some authors use the terms enqueue and dequeue for the add and remove operations.

== THE JCF Queue INTERFACE

As shown in Figure 4.1 on page 70, the Java Collections Framework includes a Queue inter- face, which is implemented by four classes: the LinkedList class, the AbstractQueue class, the PriorityQueue class, and the ArrayDeque class. For simple FIFO queues, the ArrayDeque class is the best choice:

[source,java]
----
Queue<String> queue = new ArrayDeque<String>();
----

This provides all the normal functionality of a queue. (See page 91.)

=== EXAMPLE 6.1 Testing a String Queue

[source,java]
----
1	public class TestStringStack {
2	    public static void main(String[] args) {
3	        Queue<String> queue = new ArrayDeque<String>();
4	        queue.add("GB");
5	        queue.add("DE");
6	        queue.add("FR");
7	        queue.add("ES");
8	        System.out.println(queue);
9	        System.out.println("queue.element(): " + queue.element());
10	        System.out.println("queue.remove(): " + queue.remove());
11	        System.out.println(queue);
12	        System.out.println("queue.remove(): " + queue.remove());
13	        System.out.println(queue);
14	        System.out.println("queue.add(\"IE\"): ");
15	        queue.add("IE");
16		    System.out.println(queue);
17		    System.out.println("queue.remove(): " + queue.remove());
18		    System.out.println(queue);
19	    }
20	}
----

The output is:

[source,java]
----
[GB, DE, FR, ES]
queue.element(): GB
queue.remove(): GB
[DE, FR, ES]
queue.remove(): DE
[FR, ES]
queue.add("IE"):
[FR, ES, IE]
queue.remove(): FR
[ES, IE]
----

The add, element, and remove operations are illustrated at lines 4, 9, and 10, respectively.

By comparing the output in Example 6.1 with that of Example 5.1 on page 103, it is easy to see that the only operational difference between a queue and a stack is the access point. With a queue, it is at the front, where the “oldest” element—the one that has been there the longest—is found. With a stack, it is at the top, where the “youngest” element—the one that arrived most recently—is found.

Notice that for the ArrayDeque class, the toString() method (invoked automatically by the println() method at line 8) displays the queue from front to back, and the stack from top to bottom. So in both cases, the access point is at the left end of the display.

== A SIMPLE Queue INTERFACE

The operational requirements of a queue can be formalized by this simple Java interface:

=== EXAMPLE 6.2 A Queue Interface

[source,java]
----
1	public interface Queue<E> {
2	    public void add(E element);
3	    public E element();
4	    public boolean isEmpty();
5	    public E remove();
6	    public int size();
7	}
----

In addition to the three required queue operations, this interface also specifies an isEmpty() method and a size() method.

Compare the Queue interface shown in Example 6.2 with the JCF’s Queue interface, shown in Figure 4.10 on page 89. It includes offer(), peek(), and poll() methods. In most situations, these are the same operations as the add(), element(), and remove() methods, respectively. If a limited-capacity queue is full, the add() method throws an IllegalStateException, while the offer() method merely returns false. If the queue is empty, the element() the remove() methods throw a NoSuchElementException, while the peek() and poll() methods merely returns null.


== AN INDEXED IMPLEMENTATION

Like stacks and other linear data structures, queues can be implemented using an ordinary array. The ArrayQueue class shown in Example 6.3 is similar to the ArrayStack class shown in Example 5.3 on page 104.

=== EXAMPLE 6.3 An ArrayQueue Implementation

[source,java]
----
1	public class ArrayQueue<E> implements Queue<E> {
2	    private E[] elements;
3	    private int front;
4	    private int back;
5	    private static final int INITIAL_CAPACITY = 4;
6
7	    public ArrayQueue() {
8	        elements = (E[]) new Object[INITIAL_CAPACITY];
9	    }
10
11	    public ArrayQueue(int capacity) {
12	        elements = (E[]) new Object[capacity];
13	    }
14
15	    public void add(E element) {
16	        if (size() == elements.length - 1) {
17	            resize();
18	        }
19	        elements[back] = element;
20	        if (back < elements.length - 1) {
21	            ++back;
22	        } else {
23	            back = 0; //wrap
24	        }
25	    }
26
27	    public E element() {
28	        if (size() == 0) {
29	            throw new java.util.NoSuchElementException();
30	        }
31	        return elements[front];
32	    }
33
34	    public boolean isEmpty() {
35	        return (size() == 0);
36	    }
37
38	    public E remove() {
39	        if (size() == 0) {
40	            throw new java.util.NoSuchElementException();
41	        }
42	        E element = elements[front];
43	        elements[front] = null;
44	        ++front;
45	        if (front == back) { // queue is empty
46	            front = back = 0;
47	        }
48	        if (front == elements.length) { // wrap
49	            front = 0;
50	        }
51	        return element;
52	    }
53
54	    public int size() {
55	        if (front <= back) {
56	            return back - front;
57	        } else {
58	            return back - front + elements.length;
59	        }
60	    }
61
62	    private void resize() {
63	        int size = size();
64	        int len = elements.length;
65	        assert size == len;
66	        Object[] a = new Object[2*len];
67	        System.arraycopy(elements, front, a, 0, len - front);
68	        System.arraycopy(elements, 0, a, len - front, back);
69	        elements = (E[])a;
70	        front = 0;
71	        back = size;
72	    }
73	}
----

Instead of storing the size counter, this implementation stores front and back indexes into the array. The front element of the queue is always at elements[front], and the back element of the queue is always at elements[back-1] (except when back = 0). The front index is advanced each time an element is removed from the queue (at line 44), and the back index is advanced each time an element is added (at line 21). In both cases, when the index reaches the end of the array, it is “advanced” to 0. This “wraps” the queue around the end of the array, like a ring, allowing array elements to be reused.

== AN INDEXED IMPLEMENTATION

We can use a doubly linked list to implement the Queue interface the same way we imple- mented the Stack interface in Example 5.4 on page 106.

=== EXAMPLE 6.4 A LinkedQueue Class

[source,java]
----
1	public class LinkedQueue<E> implements Queue<E> {
2	    private Node<E> head = new Node<E>(); // dummy node
3	    private int size;
4
5	    public void add(E element) {
6	        head.prev = head.prev.next = new Node<E>(element, head.prev, head);
7	        ++size;
8	    }
9
10	    public E element() {
11	        if (size == 0) {
12	            throw new java.util.EmptyStackException();
13	        }
14	        return head.next.element; // front of queue // next <--> prev
15	    }
16
17	    public boolean isEmpty() {
18	        return (size == 0);
19	    }
20
21	    public E remove() {
22	        if (size == 0) {
23	            throw new java.util.EmptyStackException();
24	        }
25	        E element =	head.next.element;	//	next	<-->	prev
26	        head.next =	head.next.next;	//	next	<-->	prev
27		    head.next.prev = head;	//	next	<-->	prev
28		    --size;
29		    return element;
30	    }
31
32		public int size() {
33		    return size;
34		}
35
36		private static class Node<E> {
37		    E element;
38		    Node<E> prev;
39		    Node<E> next;
40
41		    Node() {
42		        this.prev = this.next = this;
43		    }
44
45		    Node(E element, Node<E> prev, Node<E> next) {
46		        this.element = element;
47		        this.prev = prev;
48		        this.next = next;
49		    }
50		}
51	}
----

The only changes that need to be made to the LinkedStack class (other than the method names) are at lines 14 and 25–27, where the next and prev fields are swapped.

== APPLICATION: A CLIENT-SERVER SYSTEM

Queues are used to implement the FIFO protocol. That is common in client-server application. For example, when cars on a toll road arrive at a toll plaza, the cars are the clients, and the toll booths are the servers. If the rate at which the cars pass through the toll booths is slower than their arrival rate, then a waiting-line builds up. That is a queue.

=== EXAMPLE 6.5 A Client-Server Simulation

This simulation illustrates object-oriented programming (OOP). Java objects are instantiated to repre- sent all the interacting clients and servers. To that end, we first define Client and Server classes.

This is an event-driven simulation, where clients arrive for service at random times and services have random durations. Each client will have an arrival time, a time when service starts, and a time when it ends. All time values will be integers.

[source,java]
----
1	public class Client {
2	    private int id;
3	    private int startTime;
4
5	    public Client(int id, int time) {
6	        this.id = id;
7	        System.out.printf("%s arrived at time %d.%n", this, time);
8	    }
9
10	    public void setStartTime(int time) {
11	        startTime = time;
12	    }
13
14	    public String toString() {
15	        return "#" + id;
16	    }
17	}
----

To trace the simulation, we have the Client constructor print its arrival time (at line 7).

Each server serves at most one client at a time, so the Server class has a client field that references that server’s client, or is null when the server is idle.

Each Server object also stores the time when it will stop serving its current client. That time is computed by adding its service time (a positive random integer) to the time when it begins serving that client. The random number generator used to generate those service times is stored as a random field in the Server object. A server’s actual service time varies with each client. But the server’s average service time is a fixed property of the server, initialized when the Server object is constructed (at line 10):

[source,java]
----
1	public class Server {
2	    private Client client;
3	    private int id;
4	    private int stopTime = -1;
5	    private double meanServiceTime;
6	    private ExpRandom random;
7
8	    public Server(int id, double meanServiceTime) {
9	        this.id = id;
10	        this.meanServiceTime = meanServiceTime;
11	        this.random = new ExpRandom(meanServiceTime);
12	    }
13
14	    public double getMeanServiceTime() {
15	        return meanServiceTime;
16	    }
17
18	    public int getStopTime() {
19	        return stopTime;
20	    }
21
22	    public boolean isIdle() {
23	        return client == null;
24	    }
25
26	    public void startServing(Client client, int time)	{
27	        this.client = client;
28	        this.client.setStartTime(time);
29	        this.stopTime = time + random.nextInt();
30	        System.out.printf("%s started serving client %s	at time %d.%n",
31	                this, client, time);
32	    }
33
34	    public void stopServing(int time) {
35	        System.out.printf("%s stopped serving client %s at time %d.%n",
36	                this, client, time);
37	        client = null;
38	    }
39
40	    public String toString() {
41	        return "Server " + "ABCDEFGHIJKLMNOPQRSTUVWXYZ".charAt(id);
42	    }
43	}
----

The startServing() method (lines 26–32) assigns a new client to the server, stores the start time in the Client object, computes and stores the stop time in its own stopTime field, and prints a report of those actions. The stopServing() method (lines 34–38) stores the stop time in the Client object and prints another report.

For a simulation to be realistic, it must use randomly generated numbers to simulate the natural uncertainty of the real word. Those random numbers should have the same distribution as the natural uncertain- ties that they represent. Service times and time between client arrivals both tend to be distributed exponentially. That means that the probability that the time t is less than a number x is stem:[p = 1 - e^{- \lambda x}].

But the Math.random() method returns numbers that are uniformly distributed in the range stem:[0 \le p \lt 1]. So to convert the random number p to the exponentially distributed random variable x, we solve the equation, obtaining stem:[x = -(1/\lambda) \ln(1 – p)]. The constant stem:[1/\lambda] is the mean of the distribution. Thus we code the nextDouble() method as shown at line 9:

[source,java]
----
1	public class ExpRandom extends java.util.Random {
2	    private double mean;
3
4	    public ExpRandom(double mean) {
5	        this.mean = mean;
6	    }
7
8	    public double nextDouble() {
9	        return -mean*Math.log(1 - Math.random());
10	    }
11
12	    public int nextInt() {
13	        return (int)Math.ceil(nextDouble());
14	    }
15	}
----

The actual simulation is performed by the main class shown below. It sets four constants for the simula- tion at lines 2–5: the number of servers, the number of clients arriving for service, the mean service time among the servers, and the mean time between arrivals for the clients.

The queue is to hold the clients that have arrived for service and are waiting for an unoccupied server. The simulation instantiates two random exponentially distributed number generators (lines 7–8) and separate arrays for the Server and Client objects (lines 9–10):

[source,java]
----
1	public class Simulation {
2	    private static final int SERVERS = 3;
3	    private static final int CLIENTS = 20;
4	    private static final double MEAN_SERVICE_TIME = 25;
5	    private static final double MEAN_ARRIVAL_TIME = 4;
6	    private static Queue<Client> queue = new ArrayDeque<Client>();
7	    private static ExpRandom randomService = new ExpRandom(MEAN_SERVICE_TIME);
8	    private static ExpRandom randomArrival = new ExpRandom(MEAN_ARRIVAL_TIME);
9	    private static Server[] servers = new Server[SERVERS];
10	    private static Client[] clients = new Client[CLIENTS];
11
12		public Simulation() {
13		    String fmt = "%-27s %6d%n";
14		    System.out.printf(fmt, "Number of servers:", SERVERS);
15		    System.out.printf(fmt, "Number of clients:", CLIENTS);
16		    System.out.printf(fmt, "Mean service time:", MEAN_SERVICE_TIME);
17		    System.out.printf(fmt, "Mean interarrival time:", MEAN_ARRIVAL_TIME);
18		    for (int i=0; i<SERVERS; i++) {
19		        double meanServiceTime = randomService.nextDouble();
20		        servers[i] = new Server(i, meanServiceTime);
21		        System.out.printf("Mean service time for %s: %4.1f%n",
22		        servers[i], servers[i].getMeanServiceTime());
23		    }
24		    int nextArrivalTime = 0;
25		    for (int t=0, clientId=0; clientId < CLIENTS; t++) {
26		        if (t == nextArrivalTime) {
27		            nextArrivalTime = t + randomArrival.nextInt();
28		            Client client = clients[clientId] = new Client(++clientId, t);
29		            queue.add(client);
30		            System.out.println("\tClient queue: " + queue);
31		        }
32		        for (Server server : servers) {
33		            if (t == server.getStopTime()) {
34		                server.stopServing(t);
35		            }
36		            if (server.isIdle() && !queue.isEmpty()) {
37		                Client client = (Client)queue.remove();
38		                System.out.println("\tClient queue: " + queue);
39		                server.startServing(client,t);
40		            }
41		        }
42		    }
43		}
44
45		public static void main(String[] args) {
46		    new Simulation();
47		}
48	}
----

The output for one run was:

[source,console]
----
Number of servers:	3
Number of clients:	12
Mean service time:	25
Mean interarrival time:	4
Mean service time for Server A: 17.2
Mean service time for Server B: 51.7
Mean service time for Server C: 24.5
#1 arrived at time 0.
        Client queue: [#1]
        Client queue: []
Server A started serving client #1 at time 0. #2 arrived at time 2.
        Client queue: [#2]
        Client queue: []
Server B started serving client #2 at time 2. #3 arrived at time 4.
        Client queue: [#3]
        Client queue: []
Server C started serving client #3 at time 4. #4 arrived at time 6.
        Client queue: [#4]
#5 arrived at time 7.
        Client queue: [#4, #5]
#6 arrived at time 11.
        Client queue: [#4, #5, #6]
Server A stopped serving client #1 at time 11.
        Client queue: [#5, #6]
Server A started serving client #4	at time	11.
#7 arrived at time 12.
        Client queue: [#5, #6, #7]
#8 arrived at time 16.
        Client queue: [#5, #6, #7,	#8]
#9 arrived at time 23.
        Client queue: [#5, #6, #7,	#8, #9]
#10 arrived at time 30.
        Client queue: [#5, #6, #7,	#8, #9,	#10]
Server C stopped serving client #3	at time	30.
        Client queue: [#6, #7, #8,	#9, #10]
Server C started serving client #5	at time	30.
Server B stopped serving client #2	at time	33.
        Client queue: [#7, #8, #9,	#10]
Server B started serving client #6	at time	33.
#11 arrived at time 34.
        Client queue: [#7, #8, #9, #10, #11]
#12 arrived at time 36.
        Client queue: [#7, #8, #9, #10, #11, #12]
----

The simulation main loop is at lines 25–42. It iterates once for each clock tick t, and continues until all the clients have arrived. If it is time for a new client to arrive, then lines 27–30 execute, setting the next arrival time, creating a new Client object, and adding the new client to the queue. Then at lines 32–41, each Server object is updated. If it is time for an active server to finish serving its client, then its stopserving() method is invoked. If a server is idle and there are clients waiting in the queue, then the next client in the queue is removed from the queue and that server begins serving it.

The output shows the progress of one run. Client #4 is the first client to have to wait in the queue, followed by #5 and #6. At time t = 11, Server A finishes serving Client #1 and begins serving Client #4, who therefore leaves the queue at that time.

By the time the next server (Server C) becomes free, at time t = 30, four more clients have arrived and are waiting in the queue. Then C begins to serve #5. At time t = 33, Server B finishes with #2 and begins serving #6. Then the queue grows back to six clients waiting when the simulation finishes at time t = 36.

The simulation in Example 6.5 is called a _time-driven simulation_ because its main loop iterates once for each tick of the clock. In contrast, an event-driven simulation is one in which the main loop iterates once for each event: a job arrival, a service begin, or a service end. Event- driven simulations are usually simpler, but they require all servers to perform at the same rate.

== Review Questions

1. Why are queues called FIFO structures?
2. Would it make sense to call a queue
a. a LILO structure?
b. a FILO structure?
3. What are the advantages and disadvantages of the linked implementation of a queue relative to the contiguous implementation?

