:stem: latexmath

= 배열

* stem:[0, 1, 2, \cdots]와 같이 번호가 매겨진 요소들의 순서로 이루어진 객체
* 요소 번호는 _인덱스 번호_
* 대괄호 연산자 []를 사용하여 인덱스 번호로 접근
** 예를 들어 a[0], a[1], a[2], ...
* 매우 효율적이기 때문에 널리 사용

== 배열의 속성

다음은 자바에서 배열의 주요 속성입니다:

.	객체(Object)
..	동적(dynamic)으로 생성
..	Object 타입 변수에 할당 가능, 즉, Object 클래스의 확장으로 동작
..	Object 클래스의 모든 메서드 호출 가능
..	배열 변수는 배열 객체에 대한 참조 보유
.. Object.clone()를 사용하여 배열 복제
.. 배열의 동등성 테스트는 Object.equals()가 아닌 Arrays.equals()를 사용
.. 배열 객체는 Cloneable하고, java.io.Serializable 함
.	배열 객체에는 변수의 연속 포함
..	이러한 변수를 배열의 구성 요소(component) 또는 요소(element)
..	구성 요소 타입이 T이면 배열 타입은 T[], 즉, 배열은 클래스로 정의되지는 않았지만, 요소 타입에서 유도된 별도의 타입
..	구성 요소 타입으로 배열 타입 가능
.. 요소의 타입은 기본 타입 또는 참조 타입
.. 참조 타입의 변수는 null이 가능하므로, 초기화 되지 않은 참조 타입의 배열 요소 기본 값은 null
. 배열의 길이는 해당 구성 요소의 수
.. 배열의 길이는 배열이 생성될 때 설정되며 변경 불가
.. 배열의 길이는 public final 인스턴스 변수(length) 참조
. 배열 인덱스 값은 0...length - 1 범위의 정수
.. 인덱스를 벗어나면 ArrayIndexOutOfBoundsException
.. 인덱스로 int, short, byte 또는 char 타입만 가능

== 배열 생성(선언과 정의)

아래의 코드는 배열을 생성하는 다양한 방법을 보여 준다.

[source,java]
----
include::./example/ArrayDefs.java[]
----

다음의 질문에 답해 보자.

. 아래 두줄의 차이는?
+
[source,java]
----
include::./example/ArrayDefs.java[lines=5..6]
----
.. 선언(declaration)
.. 초기화(initialization)
.. 정의(definition)
. isPrime과 fib의 차이는?
+
[source,java]
----
include::./example/ArrayDefs.java[lines=8..9]
----
.. isPrime의 초기값은?
.. 선언 형식이 어떻게 다른가?
. 배열 a와 b는 무엇이 같고 무엇이 다른가?
+
[source,java]
----
include::./example/ArrayDefs.java[lines=10..11]
----
.. 배열의 크기는?
. 아래에서 a[4][65]를 a[3][65]로 변경한다면?
+
[source,java]
----
include::./example/ArrayDefs.java[lines=15]
----
. objects는 다양한 타입의 배열들로 구성된다.
+
[source,java]
----
include::./example/ArrayDefs.java[lines=16]
----
.. 문제가 없다면 왜?
.. 문제가 있다면 어떠한 문제가?

=== 문제. 다음에서 요구하는 배열을 생성하라.

* 1에서 9까지의 정수를 저장하고 있는 배열 a
* 배열 a의 각 요소가 홀수인지를 확인한 결과 배열 b
* 배열 a를 반지름으로 갖는 원들의 면적을 배열 c
* 구구단을 저장하는 배열 d


== 배열 요소 참조

* 정수 타입의 인덱스를 이용해 참조 가능
* 인덱스의 크기에 상관없이 일정한 시간
* 동일한 타입의 데이터를 0개 이상 가짐
* 특정 요소를 참조 하거나 변경 가능

=== 배열 요소의 변경

* 배열의 요소가
** primitive 데이터 타입이면 값 변경
** reference 데이터 타입이면 객체 변경

=== 배열 예외 처리

* ArrayIndexOutOfBoundsException
** 배열에서 허용하는 범위의 인덱스를 벗어남
** RuntimeException으로써, 실행 중 발생할 수 있으며 배열 요소 참조시 대비

=== 문제. 앞에서 생성한 배열을 이용해 참조와 변경을 확인해 보자.

*

== 배열 크기

* 배열은 크기는 생성 후 변경 불가
* 크기 변경을 위해서는 새로운 배열 생성 후 기존 데이터 복사
* 배열 크기는 배열 객체의 length 필드를 통해 확인 가능


== 배열 요소 검색

=== 순차 검색 알고리즘(The Sequential Search Algorithm)

* _선형 검색_
** 각 요소를 처음부터 순차적으로 검사하여 키 요소를 찾거나 배열의 끝에 도달할 때까지 계속
* 가장 간단한 검색 알고리즘
* 가장 효율성이 낮음

**알고리즘**

* 사후 조건: stem:[s_{i} = x]인 인덱스 i가 반환되거나 -1이 반환

1.	i가 0부터 n - 1까지 반복하면서 단계 2-3을 반복
2.	(불변: 부분 시퀀스 stem:[\{s_{0}...s_{i-1}\}]에 있는 요소는 모두 x와 같지 않음)
3.	stem:[s_{i} = x]인 경우, i 반환
4.	끝까지 찾지 못한 경우, -1 반환


==== 예제. 순차 검색을 확인해 보자.

[source,java]
----
include::./example/TestSequentialSearch.java[]
----

결과 출력은 아래와 같다.

[source,console]
----
[22, 33, 44, 55, 66, 77, 88, 99]
search(a, 44): 2
search(a, 50): -1
search(a, 77): 5
search(a, 100): -1
----

. 검색은 잘 동작하는가?
. 찾고자하는 데이터가 없을 경우, 배열의 끝까지 검색은 하는가?
. 데이터를 정수에서 문자열로 변경해서도 동일하게 동작하는가?
.. 문제가 있다면 어떠한 문제가 있는가?
. 정수나 문자열이 아닌 새로운 클래스를 정의하여도 동일하게 동작하는가?

=== 이진 검색 알고리즘(The Binary Search Algorithm)

* 정렬된 시퀀스를 검색하는 표준 알고리즘
* 순차 검색보다 훨씬 효율적이지만 *요소가 정렬되어 있어야 함*
* 시퀀스를 반으로 나누고 검색하는 요소가 포함할 것으로 예상되는 절반으로 검색 범위 제한

사전에서 단어를 찾을 때 이진 검색을 사용할 수 있습니다.

**알고리즘**

* 전제 조건: stem:[s = \{s_{0}, s_{1}, \cdots, s_{n-1}\}]은 x와 동일한 타입의 n개의 값으로 구성된 정렬된 시퀀스
* 사후 조건: 인덱스 i가 반환되어야 할 stem:[s_{i} = x]가 있는 경우, 또는 -1 반환

1.	ss를 시퀀스 s의 부분 시퀀스로 정의하고, 초기에 ss를 s와 동일하게 설정
2.	부분 시퀀스 ss가 비어 있다면, -1 반환
3.	(불변식: x가 시퀀스 s에 있다면, 그것은 부분 시퀀스 ss에 있어야 함)
4.	stem:[s_{i}]를 ss의 중간 요소로 설정
5.	stem:[s_{i}]가 x와 같다면, 해당하는 인덱스 i 반환
6.	stem:[s_{i}]가 x보다 작다면, stem:[s_{i}] 위에 있는 부분 시퀀스에 대해 단계 2-7 반복
7.	stem:[s_{i}]가 x보다 크다면, stem:[s_{i}] 아래에 있는 부분 시퀀스에 대해 단계 2-7 반복


==== 예제. 이진 검색을 확인해 보자.

[source,java]
----
include::./example/TestBinarySearch.java[]
----

* 44를 검색하기 위해 어떠한 과정이 수행되는가?
* 검색에서 가장 오래 걸린 경우 몇번을 반복하는가?
* 검색하고자하는 요소가 존재하지 않는다면 몇번을 반복하는가?
* 배열의 길이가 2배 늘어난다면 검색의 횟수는 어떻게 되는가?
** stem:[O(\lg n)]

== 배열 복제

* 배열을 동일한 크기와 요소를 갖도록 다른 배열을 만듦
* Object.clone() 메소드 사용
* Arrays.copyOf() 메소드 사용
* Arrays.copyOfRange() 메소드 사용

=== Object.clone()을 이용한 배열 복제

* 배열은 객체이기 때문에 Object.clone()을 이용해 복제 가능

==== 예제. Object.clone()을 이용ㅎ 배열을 복제해 보자.

[source,java]
----
include::./example/DuplicatingArrays.java[]
----

결과는 아래와 같다.

[source,console]
----
a : {22, 44, 66, 88}
b : {22, 44, 66, 88}
c : {AB, CD, EF}
d : {AB, CD, EF}
c : {AB, XYZ, EF}
d : {AB, CD, EF}
e : {AB, CD, EF}
f : {AB, CD, EF}
e : {AB, CDCD, EF}
f : {AB, CDCD, EF}
----

. 정수 타입 배열 b는 배열 a와 동일하게 복제 되었는가?
+
[source,code]
----
include::./example/DuplicatingArrays.java[lines=5..8]
----
. 문자열 타입 배열 b는 배열 c와 동일하게 복제 되었는가?
+
[source,code]
----
include::./example/DuplicatingArrays.java[lines=9..12]
----
. c[1]을 변경하였는데, 복제된 배열 d에는 어떠한 영향이 있는가?
+
[source,code]
----
include::./example/DuplicatingArrays.java[lines=13..15]
----
. StringBuilder 타입으로 배열 e와 f를 생성하고, e[1]을 변경하였다. 복제된 배열 f에는 어떠한 영향이 있는가?
+
[source,code]
----
include::./example/DuplicatingArrays.java[lines=17..23]
----

=== Arrays.copyOf()를 이용한 배열 복제

* 인수로 주어진 배열에서 주어진 길이만큼을 복제하여 새로운 배열 생성 후 반환
* 소스 배열보다 요청한 크기가 클 경우, 해당 타입의 기본값으로 설정(기본 생성자 아님)

=== Arrays.copyOfRange()를 이용한 배열 복제

* copyOf()와 비슷한 기능을 수행하지만, 소스 배열에서 시작과 끝 지정 가능
* 복제시 클래스 정보를 제공할 경우, 다른 타입의 배열로 변환 가능
** 다른 타입은 소스 데이터가 변환 가능한 경우에 한해 적용 가능

==== 예제. Arrays.copyOfRange()를 이용해 배열을 복제해 보자.

[source,java]
----
include::./example/TestCopyOfRange1.java[]
----

==== 문제. 다음 조건을 만족하도록 배열을 복제하라.

* 정수 10개 배열 생성
* 배열의 3번째부터 8번째까지의 요소를 Arrays.copyOfRange를 이용해 Number 배열로 복제

[source,java]
----
include::./example/TestCopyOfRange2.java[lines=1..9]
...
include::./example/TestCopyOfRange2.java[lines=12..15]
----

**결과는 아래와 같다**

[source,console]
----
[1, 1, 2, 3, 5, 8, 13]
[5, 8]
----


==== 문제. 다음 조건을 만족하도록 배열을 복제하라.

* 정수를 가질 수 있는 Box 클래스 정의
** 저장된 정수를 가져오거나 변경 가능
** up() 호출시, 저장된 정수를 1 증가 시킴
** toString() 호출시, 정수 출력
* 정수 1~10까지 10개를 순서대로 각각의 Box에 담아 배열 생성
* Box 배열의 3번째부터 5번째까지의 요소를 copyOfRange()를 이용해 복제
* 복제된 배열들의 요소를 up() 시킴
* 원 소스 배열 출력 후 확인

**결과는 아래와 같다**

[source,console]
----
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[4, 5, 6]
[5, 6, 7]
----

=== java.util.Arrays 클래스

* 배열을 처리하기 위한 특별한 유틸리티 클래스
* Arrays 클래스에서 지원하는 sort(), binarySearch(), fill(), equals() 활용

[source,java]
----
1	import java.util.Arrays;
2
3	public class TestArrays {
4	    public static void main(String[] args) {
5	        int[] a = {44, 77, 55, 22, 99, 88, 33, 66};
6	        print(a);
7	        Arrays.sort(a);
8	        print(a);
9	        int k = Arrays.binarySearch(a, 44);
10	        System.out.printf("Arrays.binarySearch(a, 44): %d%n", k);
11	        System.out.printf("a[%d]: %d%n", k, a[k]);
12	        k = Arrays.binarySearch(a, 45);
13	        System.out.printf("Arrays.binarySearch(a, 45): %d%n", k);
14	        int[] b = new int[8];
15	        print(b);
16	        Arrays.fill(b, 55);
17	        print(b);
18	        System.out.println("Arrays.equals(a,b): " + Arrays.equals(a,b));
19	    }
20	}
----

The output is

[source,console]
----
44 77 55 22 99 88 33 66
22 33 44 55 66 77 88 99
Arrays.binarySearch(a, 44): 2
a[2]: 44
Arrays.binarySearch(a, 45): -4
0 0 0 0 0 0 0 0
55 55 55 55 55 55 55 55
Arrays.equals(a,b): false
----

. 정수 배열에 대해 sort, binarySearch, fill 등의 동작을 확인 했나?
. 정수를 String으로 변경하여 동일한 과정을 수행하고 정수 배열과의 차이를 확인해 보자.
. int, String과 같이 기존에 정의되어 있던 타입 외에 별도의 클래스를 정의하여 동일한 과정을 수행 후 비교해 보자.



== 복습 문제

1. 배열의 구성요소(component)와 요소(element)의 차이는 무엇인가요?
2. 자바가 다차원 배열을 허용하지 않는다는 것은 무엇을 의미하나요?
3. ArrayIndexOutOfBoundsException 예외는 무엇이고, 그 사용 방법은 C나 C++과 같은 다른 언어와 어떻게 다른가요?
4. 배열 인덱스에 대해 유효한 타입은 무엇인가요?
5. 다음 정의에 무엇이 잘못되었나요:
   Arrays arrays = new Arrays();
6. 객체 배열을 출력하는 가장 간단한 방법은 무엇인가요?
7. 이진 검색이 순차 검색보다 훨씬 빠르다면, 후자가 언제 사용될까요?
8. 배열에서 두 번 이상 발생하는 요소에 순차 검색이 적용된다면 어떻게 될까요?
9. 배열에서 두 번 이상 발생하는 요소에 이진 검색이 적용된다면 어떻게 될까요?

== 문제

1. 배열의 fill() 메서드가 객체 배열을 어떻게 처리하는지 보기 위해 테스트 프로그램을 실행하세요.
+
{sp}+

2. 순차 검색이 10,000개 요소 배열에서 실행하는데 50ms가 걸렸다면, 동일한 컴퓨터에서 20,000개 요소 배열에서는 얼마나 걸릴 것으로 예상합니까?
+
{sp}+

3. 이진 검색이 1,000개 요소 배열에서 실행하는데 5ms가 걸렸다면, 동일한 컴퓨터에서 1,000,000개 요소 배열에서는 얼마나 걸릴 것으로 예상합니까?
+
{sp}+

4. 보간 검색(interpolation search)은 이진 검색과 동일하지만, 4단계에서 요소 stem:[s_{i}]는 ss 서열에서 stem:[s_{i}]보다 작은 요소의 비율이 균등 분포에서 예상되는 비율과 같도록 선택됩니다. +
예를 들어, 2,600페이지의 전화번호부에서 “Byrd”라는 이름을 찾을 때, 약 2/26의 이름이 그 앞에 있을 것으로 예상하여 처음에는 200페이지 근처를 엽니다. +
보간 검색은 stem:[O(\log(\log n))] 시간에 실행되는 것으로 보여집니다. 1,000개 요소 배열에서 이진 검색을 실행하는데 5ms가 걸렸다면, 동일한 컴퓨터에서 1,000,000개 요소 배열에서는 얼마나 걸릴 것으로 예상합니까?
* 이진 검색은 절반씩 줄어 들어, stem:[log_{2} n] 만큼의 검색 횟수를 갖는다.
+
{sp}+


5. 10,000개 요소 배열에서 예제 2.5의 이진 검색 메서드에 대한 테스트 드라이버를 실행하고 반복 횟수를 계산하세요.
+
{sp}+

6. 배열 a가 정렬되어 있는지 확인하는 메서드를 작성하고, 테스트하세요.
+
[source,java]
----
boolean isSorted(int[] a)
----
{sp}+

7. 배열 a[]의 최소 요소를 반환하는 메서드를 작성하고, 테스트하세요.
+
[source,java]
----
int minimum(int[] a)
----
{sp}+

8. 배열 a[]의 모든 요소의 평균 값을 반환하는 메서드를 작성하고, 테스트하세요.
+
[source,java]
----
double mean(double[] a)
----
{sp}+

9. 배열에서 중복되는 제거한 배열을 생성하여 반환하는 메서드를 작성하고, 테스트하세요.
+
[source,java]
----
int[] withoutDuplicates(int[] a)
----
{sp}+

10. 배열의 요소를 뒤집는 메서드를 작성하고, 테스트하세요.
+
[source,java]
----
void reverse(int[] a)
----
{sp}+

11. 배열 a[]와 b[]의 모든 요소를 포함하는 배열을 생성해 반환하는 메서드를 작성하고, 테스트하세요.
+
[source,java]
----
Object[] concatenate(Object[] a, Object[] b)
----
{sp}+

12. 배열의 요소를 무작위로 섞는 메스드를 작성하고, 테스트하세요.
+
[source,java]
----
void shuffle(Object[] a)
----
{sp}+

13. 주어진 문자열에서 대소문자 구분 없이 문자 빈도를 계산한 26개의 정수 배열을 반환하는 메서드를 작성하고, 테스트하세요.
+
[source,java]
----
int[] tally(String string)
----
{sp}+

14. 배열의 각 요소를 곱하여 그 합을 반환하는 메서드를 작성하고, 테스트하세요.
+
[source,java]
----
double innerProduct(double[] x, double[] y)
----
* stem:[innerProdut(x,y) = \sum\limits_{i=0}^{n} x \lbrack i \rbrack y \lbrack i \rbrack]
{sp}+

15. 두 배열의 대수적 외적(algebraic outer product)을 계산하는 메서드를 작성하고, 테스트하세요.
+
[source,java]
----
double[][] outerProduct(double[] x, double[] y)
----
* stem:[p\lbrack i \rbrack \lbrack j \rbrack = a \lbrack i \rbrack * b \lbrack j \rbrack]
{sp}+

16. 두 배열의 행렬 곱하여 반환하는 메서드를 작성하고, 테스트하세요.
+
[source,java]
----
double[][] product(double[][] a, double[][] b)
----
* stem:[p \lbrack i \rbrack \lbrack j \rbrack = \sum\limits_{k=0}^{n} a\lbrack i \rbrack \lbrack k \rbrack \times b \lbrack k \rbrack \lbrack j \rbrack]
{sp}+

17. 배열의 전치 행령을 생성하여 반환하는 메서드를 작성하고, 테스트하세요.
+
[source,java]
----
double[][] transpose(double[][] a)
----
* stem:[ta \lbrack i \rbrack \lbrack j \lbrack = a \lbrack j \rbrack \lbrack i \rbrack]
{sp}+

18. 주어진 크기의 파스칼 삼각형을 생성하는 메서드를 작성하고, 테스트하세요.
+
[source,java]
----
int[][] pascal(int size)
----
* 파스칼 삼각형은 다음과 같습니다.
  . 숫자가 들어갈 칸을 첫 번째 줄에는 1개, 두 번째 줄에는 2개, 세 번째 줄에는 3개 이런 식으로 한 줄씩 내려가면 한 칸씩 늘어나게 정삼각형 모양으로 만든다.
  . 첫 번째 줄과 두 번째 줄의 3칸에는 1을 쓴다.
  . 세 번째 줄부터는 줄의 양쪽 끝 칸에는 1을 쓰고 나머지 칸에는 바로 윗줄에 위치한 칸 중 해당 칸과 인접해 있는 두 칸의 숫자를 더해서 그 값을 쓴다.
* 첫 5줄의 출력은 다음과 같아야 합니다.
+
[source,console]
----
[1]
[1, 1]
[1, 2, 1]
[1, 3, 3, 1]
[1, 4, 6, 4, 1]
----
{sp}+

19. 에라토스테네스의 체를 작성하고, 크기가 1000인 체를 만들어 테스트하세요.
+
[source,java]
----
boolean[] initializeSieve(int n);
----
* 에라토스테니스의 체는 i번째 요소가 소수일 때만 true인 boolean 요소의 배열입니다
+
전제 조건: p는 n 비트 배열입니다. +
사후 조건: p[i]는 i가 소수일 때만 true입니다.
+
. p[0]과 p[1]을 false로 초기화하고, 다른 모든 p[i]는 true로 초기화합니다.
. 3부터 n까지 각 i에 대해 2씩 증가하며 3단계를 반복합니다.
. i를 나누는 제곱근 이하의 소수가 있으면 p[i]를 false로 설정합니다.
* 첫 5줄의 출력은 다음과 같아야 합니다.
+
[source,console]
----
    2    3    5    7   11   13   17   19   23   29   31   37   41   43   47   53
   59   61   67   71   73   79   83   89   97  101  103  107  109  113  127  131
  137  139  149  151  157  163  167  173  179  181  191  193  197  199  211  223
  227  229  233  239  241  251  257  263  269  271  277  281  283  293  307  311
  313  317  331  337  347  349  353  359  367  373  379  383  389  397  401  409
----
+
{sp}+
+
20. java.util.Vector 객체를 이용해 에라토스테네스의 체를 작성하고, 크기가 1000인 체를 만들어 테스트하세요.
+
[source,java]
----
Vector<Boolean> initializeSieve(int n);
----
{sp}+
+
21. java.util.BitSet 객체를 이용해 에라토스테네스의 체를 작성하고, 크기가 1000인 체를 만들어 테스트하세요.
+
[source,java]
----
BitSet initializeSieve(int n);
----
{sp}+
+
22. 다음 메서드가 있는 Primes 클래스를 정의하고 테스트하세요:
+
[source,java]
----
public class Primes {
    private static final int SIZE = 1000;
    private static int size = SIZE;
    private static BitSet sieve = new BitSet(size);
    private static int last = 1;

    // 다음과 같은 정적 초기화 블록을 포함하여 에라토스테네스의 체를 구현합니다.
    static {
        for (int i = 2; i < SIZE; i++) {
            sieve.set(i);
        }
        for (int n = 2; 2*n < SIZE; n++) {
            if (sieve.get(n)) {
                for (int m=n; m*n<SIZE; m++) {
                    sieve.clear(m*n);
                }
            }
        }
    }

    // last 설정
    public static void setLast(int last) {
        //...
    }

    // 비트셋 크기 설정
    public static void sizeSize(int size) {
        //...
    }

    // 비트셋 크기를 1000으로 설정
    public static void sizeSize() {
        //...
    }

    // n이 소수이면 true
    public static boolean isPrime(int n) {
        //...
    }

    // last 이후의 다음 소수
    public static int next() {
        // ...
    }

    // 체를 출력
    public static void printPrimes() {
        //...
    }
}
----
* java.util.BitSet를 이용해 구현한 에라토스테네스의 체를 사용하세요.
{sp}+

23. 다음 메서드를 Primes 클래스에 추가하고 테스트하세요.
+
[source,java]
----
public static String factor(int n)
// 전제 조건: n > 1
// n의 소인수 분해를 반환합니다;
// 예: factor(4840)은 "2*2*2*5*11*11"을 반환합니다.
----
{sp}+

24. 골드바흐의 추측을 확인하기 위한 메서드를 작성하고, 테스트하세요.
+
[source,java]
----
int [][] goldbachNumber(int n);
----
* Christian Goldbach(1690–1764)는 1742년에 2보다 큰 모든 짝수는 두 소수의 합으로 표현된다고 추측했습니다.
* 앞에서 작성한 Primes 클래스를 사용합니다.
* 첫 10줄의 출력은 다음과 같아야 합니다.
+
[source,console]
----
4 = 2+2
6 = 3+3
8 = 3+5
10 = 3+7 = 5+5
12 = 5+7
14 = 3+11 = 7+7
16 = 3+13 = 5+11
18 = 5+13 = 7+11
20 = 3+17 = 7+13
22 = 3+19 = 5+17 = 11+11
----
{sp}+

25. 모든 페르마 소스(Fermat Prime)를 찾기 위한 메서드를 작성하고, 테스트하세요.
+
[source,java]
----
int[] fermatPrime(int n);
----
* Pierre de Fermat(1601–1665)는 어떤 정수 p에 대해 stem:[n = 2^{2^{p}}+1] 형태의 소수가 무한히 많다고 추측했습니다. 이러한 수를 Fermat 소수라고 합니다. 예를 들어, 5는 소수이고 stem:[2^{2^{1}} + 1] 형태이므로 Fermat 소수입니다.
* 앞에서 작성한 Primes 클래스를 사용합니다.
* 첫 5줄의 출력은 다음과 같아야 합니다.
+
[source,console]
----
2^0 + 1 = 3
2^1 + 1 = 5
2^2 + 1 = 17
2^3 + 1 = 257
2^4 + 1 = 65537
----
{sp}+

26. Babbage prime을 찾기 위한 메서드를 작성하고, 테스트하세요.
+
[source,java]
----
int[] babbagePrime(int n);
----
* 찰스 배비지(Charles Babbage 1792-1871)는 1823년에 정부 보조금을 처음으로 받아내어 차분 기관을 만들기 위해 £1000를 받았습니다. 그의 보조금 제안서에서, Babbage는 그의 컴퓨터가 stem:[x^2 + x + 41] 공식을 표로 작성할 것이라고 예를 들었습니다. 이 함수는 많은 소수를 생성하기 때문에 수학자들에게 흥미로웠습니다.
* stem:[n = x^2 + x + 41] 형태의 소수를 Babbage 소수라고 할 수 있습니다.
* 앞에서 작성한 Primes 클래스를 사용합니다.
* 첫 5 줄의 출력은 다음과 같아야 합니다.
+
[source,console]
----
0 41 is prime
1 43 is prime
2 47 is prime
3 53 is prime
4 61 is prime
----
{sp}+

27. 쌍둥이 소수를 찾아 출력하는 프로그램을 작성하세요.
+
[source,java]
----
int[] twinPrime(int max);
----
* 두 연속된 홀수가 모두 소수일 때, 이를 쌍둥이 소수라고 하며, 무한히 많을 것이다.
* 앞에서 작성한 Primes 클래스를 사용합니다.
* 결과는 반환된 배열중 앞에서부터 두개씩 쌍으로 구성됩니다.
* 첫 5줄의 출력은 다음과 같아야 합니다.
+
[source,console]
----
3 5
5 7
11 13
17 19
29 31
----
{sp}+

28. 각 연속된 제곱수 쌍 사이에 적어도 하나의 소수가 있다는 가설을 테스트하세요.
+
[source,java]
----
int findPrime(int min, int max);
----
* 제곱수는 1, 4, 9, 16, 25, ...입니다.
* 앞에서 작성한 Primes 클래스를 사용하세요.
* 첫 5줄의 출력은 다음과 같아야 합니다.
+
[source,console]
----
1 < 2 < 4
4 < 5 < 9
9 < 11 < 16
16 < 17 < 25
25 < 29 < 36
----
{sp}+

29. 메르센 소수(Mersenne prime)를 찾아 출력하는 프로그램을 작성하세요.
+
[source,java]
----
boolean isMersennePrime(int p);
----
* Minimite 수도사 Marin Mersenne(1588–1648)는 p가 소수일 때 stem:[n = 2^p - 1] 형태의 수를 연구했습니다. 그는 대부분의 n이 소수일 것이라고 믿었습니다. 이제 이 수는 Mersenne 소수라고 합니다.
* 앞에서 작성한 Primes 클래스를 사용하세요.
* 첫 5줄의 출력은 다음과 같아야 합니다.
+
[source,console]
----
2 2^2-1 = 3 is prime
3 2^3-1 = 7 is prime
5 2^5-1 = 31 is prime
7 2^7-1 = 127 is prime
11 2^11-1 = 2047 is not prime
----
{sp}+

30. 2부터 시작되는 소수 n개를 찾고, 이중 회문을 찾아 출력하는 프로그램을 작성하세요.
* 숫자가 뒤집혀도 동일할 때, 그 숫자를 회문이라고 합니다. +
예를 들어, 3456543은 회문입니다.
* 앞에서 구현한 Primes 클래스를 이용합니다.