:sourcedir: ../src/data_structures_and_algorithms/src/main/java/com/nhnacademy/queue

= 5. Queue(큐)

* 먼저 들어온 것이 먼저 나가는 선입선출(FIFO)을 구현한 컬렉션
* 접근할 수 있는 유일한 객체가 삽입된 첫 번째 객체
* 예
** 대기 줄

== 5.1. 큐의 연산

* euqueue - 큐에 요소 추가
* dequeue - 큐의 맨 앞 요소 제거
* peek - 큐의 맨 앞 요소 참조

image::./images/queue.svg[align=center]

== 5.2. 간단한 Queue Interface

* 큐의 기본 연산으로만 정의

[source,java]
----
public interface Queue {
    void enqueue(int element);
    int dequeue();
    int peek();
}
----

== 5.3. 배열을 이용한 큐 구현

* 큐에 입력되는 요소들을 배열로 이용해 관리
** 인덱스를 이용한 접근으로 빠르고 간편
* 초기 배열 크기 지정
** 배열이 고정될 경우, 배열 크기 내에서만 사용 가능

=== 예제 1. 배열을 이용해 ArrayQueue를 작성하고, 테스트하세요.

* 큐에서 요소 관리를 위한 자료 구조로 배열 사용
* toString()을 이용해 큐 출력

**수행 결과**

[source,console]
----
queue : []
euqueue 1 : [1]
euqueue 2 : [1,2]
euqueue 3 : [1,2,3]
euqueue 4 : [1,2,3,4]
euqueue 5 : [1,2,3,4,5]
dequeue [2,3,4,5] : 1
dequeue [3,4,5] : 1
dequeue [4,5] : 1
dequeue [5] : 1
dequeue [] : 1
----

=== 문제 1. 앞에서 작성한 ArrayQueue를 이용해 요청되는 추가 기능을 작성하고, 테스트하세요.

* 큐에서 가지고 있는 요소 수를 알 수 있는 size()
* 큐가 비어 있는지 확인 가능한 isEmpty()
* 큐에 설정된 배열이 다 찼을 경우,
** 배열의 크기 변경

**테스트 코드**
[source,java]
----
include::{sourcedir}/Problem01.java[lines=77..112,indent=0]
----

**수행 결과**

[source,console]
----
        Command | isEmpty | Size | Elements
 queue.queue(1) |   false |    1 | [1]
 queue.queue(2) |   false |    2 | [1, 2]
 queue.queue(3) |   false |    3 | [1, 2, 3]
 queue.queue(4) |   false |    4 | [1, 2, 3, 4]
 queue.queue(5) |   false |    5 | [1, 2, 3, 4, 5]
queue.dequeue() |   false |    4 | [2, 3, 4, 5]
queue.dequeue() |   false |    3 | [3, 4, 5]
queue.dequeue() |   false |    2 | [4, 5]
queue.dequeue() |   false |    1 | [5]
queue.dequeue() |    true |    0 | []
----

=== 문제 2. 앞에서 구현한 ArrayQueue에는 치명적인 문제가 있다. 확인하고 수정한 후 테스트하세요.

* 아래의 과정 수행 후 문제점 확인
** ArrayQueue에 배열 크기를 알 수 있는 getCapacity() 메서드 추가
** 요소 하나를 넣었다 빼기를 반복
* 문제점은? 해결하기 위한 방법은?
** link:https://en.wikipedia.org/wiki/Circular_buffer[Circular Buffer(링버퍼)]

**테스트 코드**

[source,java]
----
include::{sourcedir}/Problem02.java[lines=152..173,indent=0]
----

**수행 결과**

[source,console]
----
     queue |   Capacity |   Elements | circularQueue |   Capacity |   Elements
     queue |          2 |         [] | circularQueue |          2 |         []
     queue |          2 |        [0] | circularQueue |          2 |        [0]
     queue |          2 |         [] | circularQueue |          2 |         []
     queue |          2 |        [1] | circularQueue |          2 |        [1]
     queue |          2 |         [] | circularQueue |          2 |         []
     queue |          7 |        [2] | circularQueue |          2 |        [2]
     queue |          7 |         [] | circularQueue |          2 |         []
     queue |          7 |        [3] | circularQueue |          2 |        [3]
     queue |          7 |         [] | circularQueue |          2 |         []
     queue |          7 |        [4] | circularQueue |          2 |        [4]
     queue |          7 |         [] | circularQueue |          2 |         []
     queue |          7 |        [5] | circularQueue |          2 |        [5]
     queue |          7 |         [] | circularQueue |          2 |         []
     queue |          7 |        [6] | circularQueue |          2 |        [6]
     queue |          7 |         [] | circularQueue |          2 |         []
     queue |         12 |        [7] | circularQueue |          2 |        [7]
     queue |         12 |         [] | circularQueue |          2 |         []
     queue |         12 |        [8] | circularQueue |          2 |        [8]
     queue |         12 |         [] | circularQueue |          2 |         []
     queue |         12 |        [9] | circularQueue |          2 |        [9]
     queue |         12 |         [] | circularQueue |          2 |         []
----

**생각해 볼 것**

* 배열 크기가 계속해서 증가하는 문제 해결
* 모든 문제가 해결되었나?
** 프로그램 시작과 함께 요소의 삽입이 10000번 발생한 후

== 5.4. Linked data를 이용한 큐 구현

배열을 이용해 큐를 구현할 경우 다음과 같은 문제들이 발생할 수 있다.

* 인덱스 증가로 인한 배열 공간 낭비
** 순환 버퍼를 이용해 해결
* 요소 유입의 급속한 증가에 따라 큰 배열 할당 후 적은 유입

=== 예제 2. Linked data를 이용해 LinkedQueue를 작성하고, 테스트하세요.

* 앞에서 정의한 Node 클래스 사용
* 앞에서 정의한 Queue를 linked data를 이용해 구현

**테스트 코드**
[source,java]
----
include::{sourcedir}/Exam02.java[lines=92..116,indent=0]
----

**수행 결과**

[source,console]
----
queue : []
queue : [ 1]
queue : [ 1,  2]
queue : [ 1,  2,  3]
queue : [ 1,  2,  3,  4]
queue : [ 1,  2,  3,  4,  5]
queue : [ 2,  3,  4,  5]
queue : [ 3,  4,  5]
queue : [ 4,  5]
queue : [ 5]
queue : []
----

=== 문제 3. 앞에서 작성한 LinkedQueue를 이용해 요청되는 추가 기능을 작성하고, 테스트하세요.

* 큐에서 가지고 있는 요소 수를 알 수 있는 size()
* 큐가 비어 있는 확인 가능한 isEmpty()

**테스트 코드**

[source,java]
----
include::{sourcedir}/Problem03.java[lines=108..132,indent=0]
----

**수행 결과**

[source,console]
----
create : 0, true, []
enqueue(1) : 1, false, [ 1]
enqueue(2) : 2, false, [ 1,  2]
enqueue(3) : 3, false, [ 1,  2,  3]
enqueue(4) : 4, false, [ 1,  2,  3,  4]
enqueue(5) : 5, false, [ 1,  2,  3,  4,  5]
dequeue() : 4, false, [ 2,  3,  4,  5]
dequeue() : 3, false, [ 3,  4,  5]
dequeue() : 2, false, [ 4,  5]
dequeue() : 1, false, [ 5]
dequeue() : 0, true, []
----

== 5.5. 효율적 자원 관리

* ArrayQueue는
** 큐에서 관리해야 하는 요소 수가 제한적일 경우, 일정 크기의 배열을 이용해 빠르게 삽입/제거 가능
** 그렇지 않으며, 빈번한 배열의 복사 또는 필요 이상의 공간 사용의 문제
* LinkedQueue는
** 큐에서 관리해야 하는 요소 수가 가변적일 경우, 필요한 공간만 확보 후 해제함으로써 효율적 메모리 활용
** 시스템에 따라 빈번한 메모리 할당/해제가 문제 될 수 있음
*** 메모리 조각화

=== 문제 4. CircularArrayQueue와 LinkedQueue를 이용해 두 큐의 자원 활용에 대해 비교해 보자.

다음 두 경우에 대해 수행 시간을 비교해 보자.

* Case 1
** CircularArrayQueue의 초기 크기를 5, 배열 증가량을 5로 생성
** 100000개의 요소를 생성하여 넣고
** 100000개를 삭제
** LinkedQueue 생성
** 100000개의 요소를 생성하여 넣고
** 100000개를 삭제

* Case 2
** CircualrArrayQueue의 초기 크기를 5, 배열 증가량을 5로 생성
** 1개의 요소를 생성하여 넣고
** 1개의 요소를 삭제하는 과정을 1000000번 반복
** LinkedQueue 생성
** 1개의 요소를 생성하여 넣고
** 1개의 요소를 삭제하는 과정을 1000000번 반복

**수행 결과**
[source,console]
----
Case 1
CircularArrayQueue : 100000 loops = 676 ms
LinkedQueue : 100000 loops = 4 ms
Case 2
CircularArrayQueue : 1000000 loops = 10 ms
LinkedQueue : 1000000 loops = 7 ms
----

**참고**

* System.currentTimeMills()
** 이용해 현재 시스템 시간을 얻어 옴
** 1970/01/01 00:00:00(link:https://en.wikipedia.org/wiki/UTC%2B00:00[UTC])부터의 시간을 밀리초 단위로 계산


== 5.6. 리뷰 질문

1. 큐가 FIFO 구조로 불리는 이유는 무엇인가요?
2. 큐를 다음과 같이 부르는 것이 의미가 있을까요?
a. LILO 구조?
b. FILO 구조?
3. 연속적인 데이터 구조를 이용한 큐의 구현과 연결 구조를 이용한 큐 구현의 장단점은 무엇인가요?


---

ifndef::github-env[]
link:../index.adoc[목록]
endif::[]

ifdef::github-env[]
link:../README.md[목록]
endif::[]