= Array(배열)


* **배열이란?**

배열(array)은 동일한 타입의 변수들로 이루어진 자료구조로, 주요 특징은 다음과 같습니다.

* 동일한 데이터 타입
** 하나의 데이터 타입
** 정수형 배열은 오직 정수만 포함
* 요소에 대한 접근
** 각 요소는 인덱스 또는 키를 이용해 접근 가능
** 인덱스는 일반적으로 0부터 시작
* 연속된 메모리 공간
** 배열은 일반적 연속된 메모리 공간에 저장
** 동일한 테이터 타입은 동일한 메모리 크기를 가지므로 인덱스를 통해 빠르게 접근
** 1차원 한정

== Java에서의 배열 선언과 정의

1. 배열은 Object
a. 실행 시간에 동적으로 생성
b. Object type의 변수 할당
c. Object 클래스의 모든 함수 호출 가능
2. 배열 객체에는 변수의 sequence가 포함된다.
3. 배열을 구성하는 변수를 배열의 component 또는 element라고 한다.
a. element type이 T이면 배열 type은 T[]이다.
b. 배열 type 변수는 배열 객체에 대한 reference를 보유한다.
c. element type이 배열 type일 수 있다.
d. 배열 element는 배열 type이 아닌 component입니다.
e. element type은 primitive type 또는 reference일 수 있다.
4. 배열의 길이는 element의 수이다.
a. 배열의 길이는 배열이 생성될 때 설정
b. 생성 후 변경 불가
c. 길이는 public final 인스턴스 변수로 접근
5. 배열 인덱스값은 0...length-1 범위의 정수이어야 한다.
a. 배열의 인덱스는 int로 변환 가능한 타입만 사용 가능(int, short, byte 또는 char)
b. 인덱스가 0...length -1을 벗어나면, ArrayIndexOutOfBoundsException 발생
6. Object.clone() 함수를 사용하여 배열 복제
7. Arrays.equals() 함수를 사용하여 배열의 동등성 테스트
8. 배열 객체는 Cloneable 및 java.io.Serializable을 구현


=== 예제. 다음 코드를 보고 배열 정의들에 대해 알아보자.

[source,java,linenums]
----
1   public class ArrayDefs {
2	    public static void main(String[] args) {
3		    float x[];
4		    x = new float[100];
5		    args = new String[10];
6		    boolean[] isPrime = new boolean[1000];
7		    int fib[]={0,1,1,2,3,5,8,13};
8		    short[][][] b = new short[4][10][5];
9		    double a[][] = {{1.1,2.2}, {3.3,4.4}, null, {5.5,6.6}, null};
10		  a[4] = new double[66];
11		  a[4][65] = 3.14;
12		  Object[] objects = {x, args, isPrime, fib, b, a};
13	  }
14  }
----

* Line 3은 x[]가 부동 소수점 배열임을 선언
** 배열에 대한 저장 공간은 미할당
* Line 4는 x[]가 100개의 부동 소수점 구성 요소를 가지도록 정의
* Line 5는 args[]가 10개의 문자열 구성 요소를 가지도록 정의
* Line 6은 isPrime[]이 boolean 변수 배열임을 선언하고, 1,000개의 부울 변수 배열로 정의
* Line 7은 fib[]가 8개의 int를 가진 배열임을 선언하고, 그 값을 나열된 8개의 값으로 초기화된 int 변수 배열로 정의
** fib[4]의 값은 3, fib[7]의 값은 13
* Line 8은 b[][][]가 3차원 배열임을 선언
** 2차원 배열을 4개 가지고
** 각각의 2차원 배열은 1차원 배열 10를 가지며
** 1차원 배열은 short 타입 5개로 구성되도록 정의
** 따라서, b[][][]는 총 4 * 10 * 5 = 200개의 short 타입 변수로 구성
* Line 9는 a[][]가 2차원 배열임을 선언
** 초기값(배열과 null)을 이용해 5개의 1차원 배열을 가지는 것으로 정의
** 초기값으로 주어진 1차원 배열은 값으로 정의된 배열이거나 null
** null로 초기화된 요소는 double 타입으로 구성된 1차원 배열로 정의 가능
** Line 10은 a[4]에 66개 요소의 double 배열 할당
** Line 11은 그 마지막 요소에 3.14 할당
* Line 12는 배열 객체가 6개의 구성 요소로 구성
** 각 구성 요소는 배열


=== 문제. 다음에서 설명하는 배열을 정의해 보자.

1. 피보나치 수열(fibonacci sequence)로 구성된 배열을 정의하고 출력하라.
+
[source,java]
----
public class ArrayDefs {
  public static void main(String[] args) {
    int [] fibos = ...;

    for(...) {
      ...
    }
  }
}
----
+
[source,console]
----
0 1 1 2 3 5 8 13 21 34
----
2. 배열의 요소들이 소수(Prime number)인 확인하고 그 결과를 배열로 저장하고 출력하라.
+
[source,java]
----
public class ArrayDefs {
  public static boolean isPrime(int number) {
    ...
  }

  public static void main(String[] args) {
    int [] fibos = ...;
    boolean [] primes = ...;

    for(...) {
      ...
    }
    System.out.println("");

    for(...) {
      ...
    }
    System.out.println("");
  }
}
----
+
[source,console]
----
0 1 1 2 3 5 8 13 21 34
false false false true true true false true false false
----
3. 배열의 요소들에 실수 값을 곱한 결과를 배열로 저장하고 출력하라.
+
[source,java]
----
public class ArrayDefs {
  ...

  public static void main(String[] args) {
    int [] fibos = ...;
    boolean [] primes = ...;
    float [] fiboFloats = ...;

    ...
  }
}
----
+
[source,console]
----
0 1 1 2 3 5 8 13 21 34
false false false true true true false true false false
0.0 0.3 0.3 0.6 0.90000004 1.5 2.4 3.9 6.3 10.200001
----
4. 실수 값을 곱해 얻은 결과 값 배열의 요소들을 문자열로 변환하여 저장하고 출력하라.
+
[source,java]
----
public class ArrayDefs {
  ...

  public static void main(String[] args) {
    int [] fibos = ...;
    boolean [] primes = ...;
    float [] fiboFloats = ...;
    float [] fiboStrings = ...;

    ...
  }
}
----
+
[source,console]
----
0 1 1 2 3 5 8 13 21 34
false false false true true true false true false false
0.0 0.3 0.3 0.6 0.90000004 1.5 2.4 3.9 6.3 10.200001
0.0 0.3 0.3 0.6 0.90000004 1.5 2.4 3.9 6.3 10.200001
----
5. 앞에서 생성한 4가지 배열들을 요소로 갖는 배열을 생성하고 출력하라.
+
[source,java]
----
public class ArrayDefs {
  ...

  public static void main(String[] args) {
    int [] fibos = ...;
    boolean [] primes = ...;
    float [] fiboFloats = ...;
    float [] fiboStrings = ...;
    Object [] objects = ...;
    ...
  }
}
----
+
[source,console]
----
0 1 1 2 3 5 8 13 21 34
false false false true true true false true false false
0.0 0.3 0.3 0.6 0.90000004 1.5 2.4 3.9 6.3 10.200001 0.0 0.3 0.3 0.6 0.90000004 1.5 2.4 3.9 6.3 10.200001
[I@7637f22 [Z@4926097b [F@762efe5d [Ljava.lang.String;@5d22bbb7
----
6. 배열 출력은 Arrays에서 지원하는 함수를 이용해 가능하다. Arrays.toString을 이용해 출력되도록 수정하라.
+
[source,java]
----
import java.util.Arrays;

public class ArrayDefs {
    public static boolean isPrime(int number) {
      ...
    }

    public static void main(String[] args) {
        int[] fibos = ...;
        boolean[] primes = ...;
        float[] fiboFloats = ...;
        String[] fiboStrings = ...;
        Object[] objects = ...;

        ...

        System.out.println(Arrays.toString(...));
    }
}
----
+
[source,console]
----
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]
[false, false, false, true, true, true, false, true, false, false]
[0.0, 0.3, 0.3, 0.6, 0.90000004, 1.5, 2.4, 3.9, 6.3, 10.200001]
[0.0, 0.3, 0.3, 0.6, 0.90000004, 1.5, 2.4, 3.9, 6.3, 10.200001]
[[I@7637f22, [Z@4926097b, [F@762efe5d, [Ljava.lang.String;@5d22bbb7]
----

**참고**

* 배열의 크기는 배열 object의 field를 직접 참조하여 알 수 있습니다.
* 출력은 for 문과 같은 반복문을 사용하거나, Arrays class에서 지원하는 함수를 이용할 수 있습니다.
* 배열의 소수는 1보다 큰 자연수 중 1과 자기 자신만을 약수로 가지고 있는 수입니다.
* Java 언어는 생각보다 똑똑하지 않습니다. 실수를 literal로 줄 경우, double과 float 중 선택하지 못합니다.
* Java의 primitive type 배열은 primitive type이 아닙니다.


== Duplicating an Array(배열 복제)

* Java에서의 배열 복제는 두가지 방법이 있습니다.
** 동일한 타입, 동일한 크기의 배열 생성 후 요소 복제
** Object 클래스의 기본 메소드인 clone

=== 문제. 다음의 설명에 따라 반복문을 이용해 배열을 복제해 보자.

1. 앞에서 생성한 fibos, objects를 이용하라.
2. fibos와 동일한 데이터 타입, 동일한 크기 배열 fibos2를 정의하고, 반복문을 이용해 요소를 복제해 넣고 fibos와  fibos2를 출력하라.
3. fibos의 첫번째 요소를 55로 변경하고, fibos와 fibos2를 출력하고 어떠한 영향이 있는지 확인하라.
4. primes, fiboFloats, fiboStrings를 fibos와 동일하게 복제하고, 이를 이용해 objects2를 생성해 출력하라.
5. fibos의 첫번째 요소를 89로 변경하고, objects와 objects2의 출력하여 어떠한 영향이 있는지 확인하라.
6. objects와 objects2의 첫번째 요소는 int 배열이다. 해당 배열의 첫번째 요소를 출력하고 어떠한 5번 과정에서 값을 변경하는 과정이 objects2에 어떠한 영향을 주었는지 확인해 보자.

=== 문제. 다음의 설명에 따라 clone을 이용해 배열을 복제해 보자.

1. 피보나치 수열(fibonacci sequence)로 구성된 배열을 정의하고 출력하라.
2. clone을 이용해 fibos를 복제하여 fibos2를 생성하고 출력하라.
3. fibos의 첫번째 요소를 55로 변경하고, fibos와 fibos2를 출력하고 어떠한 영향이 있는지 확인하라.
4. clone을 이용해 objects를 복제하여 objects2를 생성하고 출력하라.
5. fibos의 첫번째 요소를 89로 변경하고, objects와 objects2를 출력하고 어떠한 영향이 있는지 확인하라.
6. objects와 objects2의 첫번째 요소는 int 배열이다. 해당 배열의 첫번째 요소를 출력하고 어떠한 5번 과정에서 값을 변경하는 과정이 objects2에 어떠한 영향을 주었는지 확인해 보자.

== Search(검색)

== Sequential Search(순차 검색)

다음의 설명에 따라 배열에서 특정 요소의 위치를 찾습니다.

* 앞에서 정의한 피보나치수열의 배열 fibos를 사용합니다.
* 반복문을 사용하여 해당 element의 위치를 순차적 찾습니다.

[source,java]
----
public class ArraySearch {
  public static int search(int [] arrays, int value) {
    ...
  }

  public static void main(String[] args) {
      int [] fibos = {0, 1, 1, 2, 3, 5, 8, 13, 21, 34};

      System.out.println(...);
      for(int value : new int[]{1, 5, 13}) {
        System.out.println(...);
      }
  }
}
----

출력은 다음과 같습니다.

[source,console]
----
[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]
1은 2번째에 위치합니다.
5는 6번째에 위치합니다.
13은 8번째에 위치합니다.
----

**참고**

* 검색 방법 중 가장 간단한 방법입니다.
* 최대 배열의 크기만큼 비교합니다.
* 주어진 값을 찾지 못한 경우, 특정한 값을 반환합니다.



== Binary Search(이분 검색)

앞에서의 순차 검색은 가장 간단한 검색 알고리즘입니다. 하지만, 검색 효율 면에서는 매우 낮은 방식입니다.

다음의 설명에 따라 배열에서 특정 요소의 위치를 찾습니다.

* 앞에서 정의한 피보나치수열의 배열 fibos를 사용합니다.
* 배열의 중간 위치에 있는 요소값이 일치하는지 확인하여 일치하면 해당 위치를 돌려줍니다.
* 그렇지 않다면, 중간 위치보다 하나 작은 위치 중에서 해당 위치값이 있는지 동일한 방법으로 찾습니다.
* 여전히 찾지 못했다면, 중간 위치보다 하나 큰 위치 중에서 해당 위치값이 있는지 동일한 방법으로 찾습니다.
* 순차적 배열 검색과 차이점이 무엇인지 생각해 봅니다.

[source,java]
----
import java.util.Arrays;

public class ArraySearch {
    public static int sequentialSearch(int [] arrays, int value) {
      ...
    }

    public static int binarySearch(int [] arrays, int firstIndex, int lastIndex, int value) {
      ...
    }

    public static void main(String[] args) {
        int [] fibos = {0, 1, 1, 2, 3, 5, 8, 13, 21, 34};

        System.out.println(Arrays.toString(fibos));
        for(int value : new int []{1, 5, 13}) {
            System.out.println("sequentialSearch : " + value + "은 "
                               + (sequentialSearch(fibos, value) + 1 )
                               + "번째에 위치합니다.");
        }

        for(int value : new int []{1, 5, 13}) {
            System.out.println("binarySearch : " + value + "은 "
                               + (binarySearch(fibos, 0, fibos.length - 1, value) + 1 )
                               + "번째에 위치합니다.");
        }
    }
}
----

출력은 다음과 같습니다.

[source,console]
----
배열 : [0, 1, 1, 2, 3, 5, 8, 13, 21, 34]
sequentialSearch : 1은 2번째에 위치합니다.
sequentialSearch : 5는 6번째에 위치합니다.
sequentialSearch : 13은 8번째에 위치합니다.
binarySearch : 1은 2번째에 위치합니다.
binarySearch : 5는 6번째에 위치합니다.
binarySearch : 13은 8번째에 위치합니다.
----

**참고**

* 배열을 반으로 나누어 검색하는 방법을 이분 검색이라고 합니다.
* 문제 해결 방법 중 동일한 함수를 다시 불러서 사용하는 recursion에 대해 생각해 봅니다.
* 위에서 설명한 검색은 문제가 있습니다. 무엇이 문제인지 설명하고, 해결 방법을 생각해 봅니다.



== 이분 검색 수정

다음의 설명에 따라 이분 검색을 수정합니다.

* 배열을 정렬합니다.
* 중간값이 찾고자 하는 값이 아닌 경우, 해당 값이 포함되어 있을 가능성이 없는 곳은 검색하지 않도록 합니다.

[source,java]
----
import java.util.Arrays;

public class ArraySearch {
    public static int sequentialSearch(int [] arrays, int value) {
      ...
    }

    public static int binarySearch(int[] arrays, int firstIndex, int lastIndex, int value) {
        if (firstIndex <= lastIndex) {
            int middleIndex = (firstIndex + lastIndex) / 2;
            if (arrays[middleIndex] == value) {
              ...
            } else if (arrays[middleIndex] < value) {
              ...
            } else {
              ...
            }
        }
        return  -1;
    }

    public static void main(String[] args) {
        int [] fibos = {0, 1, 1, 2, 3, 5, 8, 13, 21, 34};

        System.out.println("배열 : " + Arrays.toString(fibos));
        for(int value : new int []{1, 5, 13}) {
            System.out.println("sequentialSearch : " + value + "은 "
                               + (sequentialSearch(fibos, value) + 1 )
                               + "번째에 위치합니다.");
        }

        Arrays.sort(fibos);
        for(int value : new int []{1, 5, 13}) {
            System.out.println("binarySearch : " + value + "은 "
                               + (binarySearch(fibos, 0, fibos.length - 1, value) + 1 )
                               + "번째에 위치합니다.");
        }
    }

}
----

== 요약정리

* 배열의 component(구성요소)와 element(요소)의 차이점은 무엇인가요?
* Java가 다차원 배열을 허용하지 않는다는 것은 무엇을 의미하나요?
* ArrayIndexOutOfBoundsException 예외는 무엇이고, 그 사용은 C나 C++과 같은 다른 언어와의 차이점이 무엇인가요?
* 배열 인덱스에 유효한 type은 무엇인가요?
* 다음 정의에서 무엇이 문제인가요?
  Arrays arrays = new Arrays();
* 객체 배열을 출력하는 가장 간단한 방법은 무엇인가요?
* 이진 검색이 순차 검색보다 훨씬 빠르다면, 후자가 언제 사용되나요?
* 순차 검색이 배열에서 두 번 이상 나타나는 요소에 적용되면 어떻게 될까요?
* 이진 검색이 배열에서 두 번 이상 나타나는 요소에 적용되면 어떻게 될까요?
