= 스택

_스택_은 후입선출(LIFO) 방식을 구현하는 컬렉션입니다. 이는 컬렉션에서 접근할 수 있는 유일한 객체가 마지막에 삽입된 객체임을 의미합니다. 책을 쌓아 올린 스택이 좋은 비유입니다. 쌓여 있는 책을 먼저 제거하지 않고는 스택에서 책을 꺼낼 수 없습니다.

== 스택 연산

스택의 기본 연산은 다음과 같습니다:

 . 스택의 맨 위에 요소를 추가합니다.
 . 스택의 맨 위에 있는 현재 요소에 접근합니다.
 . 스택의 맨 위에 있는 현재 요소를 제거합니다. 이 세 가지 연산은 보통 각각 푸시(push), 피크(peek), 팝(pop)이라고 불립니다.

== JCF Stack 클래스

70페이지의 그림 4.1에서 보여주듯이, Java 컬렉션 프레임워크(JCF)에는 특수화된 리스트 타입인 Vector 클래스가 포함되어 있습니다. JCF가 개발되기 전에, Java는 Vector 클래스를 확장하여 Stack 클래스를 만들었습니다. 그러나 그 클래스는 이제 JCF와 일관되지 않기 때문에 구식으로 간주됩니다. 대신, Java API는 스택을 위해 ArrayDeque 클래스를 사용하는 것을 권장합니다. 예를 들어 다음과 같습니다:


[source,java]
----
Deque<String> stack = new ArrayDeque<String>();
----
This provides all the normal functionality of a stack, while being consistent with the JCF. (See page 91.)

=== EXAMPLE 5.1 Testing a String Stack

[source,java]
----
1	public class TestStringStack {
2	public static void main(String[] args) {
3	Deque<String> stack = new ArrayDeque<String>();
4	stack.push("GB");
5	stack.push("DE");
6	stack.push("FR");
7	stack.push("ES");
8	System.out.println(stack);
9	System.out.println("stack.peek(): " + stack.peek());
10		System.out.println("stack.pop(): " + stack.pop());
11		System.out.println(stack);
12		System.out.println("stack.pop(): " + stack.pop());
13		System.out.println(stack);
14		System.out.println("stack.push(\"IE\"): ");
15		stack.push("IE");
16		System.out.println(stack);
17	}
18	}
----

The output is:

[source,console]
----
[ES, FR, DE, GB]
stack.peek(): ES
stack.pop(): ES
[FR, DE, GB]
stack.pop(): FR
[DE, GB]
stack.push("IE"):
[IE, DE, GB]
----

푸시(push), 피크(peek), 그리고 팝(pop) 연산은 각각 4번, 9번, 그리고 10번 줄에 예시되어 있습니다.

== 스택 인터페이스

스택의 연산 요구 사항(피크, 팝, 푸시)은 Java 인터페이스로 공식화할 수 있습니다:

=== 예제 5.2 스택 인터페이스

[source,java]
----
1	public interface Stack<E> {
2	public boolean isEmpty();
3	public E peek();
4	public E pop();
5	public void push(E element);
6	public int size();
7	}
----

기호 E는 타입 매개변수입니다. (76페이지 참조.) 이는 스택의 지연된 요소 타입을 나타냅니다.

필수적인 세 가지 스택 연산 외에도, 이 인터페이스는 isEmpty() 메서드와 size() 메서드도 명시합니다.

예제 5.2에 나온 Stack 인터페이스는 제네릭 타입입니다. (76페이지 참조.) 1번 줄의 <E> 표현은 요소 타입 E가 명시되지 않았음을 의미합니다.

== 인덱스 기반 구현

Stack 인터페이스를 구현하는 방법은 여러 가지가 있습니다. 그 중 가장 간단한 방법은 일반 배열을 사용하는 인덱스 기반 구현입니다.


=== EXAMPLE 5.3 An ArrayStack Implementation

[source,java]
----
1	public class ArrayStack<E> implements Stack<E> {
2	    private E[] elements;
3	    private int size;
4	    private static final int INITIAL_CAPACITY = 100;
5
6		public ArrayStack() {
7		    elements = (E[]) new Object[INITIAL_CAPACITY];
8		}
9
10		public ArrayStack(int capacity) {
11		    elements = (E[]) new Object[capacity];
12		}
13
14		public boolean isEmpty() {
15		    return (size == 0);
16		}
17
18		public E peek() {
19		    if (size == 0) {
20		        throw new java.util.EmptyStackException();
21		    }
22		    return elements[size-1]; // top of stack
23		}
24
25		public E pop() {
26		    if (size == 0) {
27		        throw new java.util.EmptyStackException();
28		    }
29		    E element = elements[--size];
30		    elements[size] = null;
31		    return element;
32		}
33
34		public void push(E element) {
35		    if (size == elements.length) {
36		        resize();
37		    }
38		    elements[size++] = element;
39		}
40
41		public int size() {
42		    return size;
43		}
44
45		private void resize() {
46		    assert size == elements.length;
47		    Object[] a = new Object[2*size];
48		    System.arraycopy(elements, 0, a, 0, size);
49		    elements = (E[])a;
50		}
51	}
----

이 클래스는 제네릭 타입 Stack<E>를 구현하므로, 역시 제네릭 타입입니다. 따라서 타입 매개변수 E는 요소 타입을 지정해야 할 때마다 사용됩니다. 예를 들어, 29번 줄에서 로컬 변수 element는 타입 E로 선언됩니다.

이 ArrayStack 구현은 "백킹 배열" elements[]를 사용하여 스택의 요소를 저장합니다. 이는 2번 줄에 E[] 타입으로 선언되어 있으며, 이는 타입 E의 요소 배열을 의미합니다. 다른 클래스 필드는 정수형 size로, 스택에 있는 요소의 수를 카운트합니다.

클래스는 4번 줄에 static 상수 INITIAL_CAPACITY를 숫자 100으로 정의합니다. 이는 7번 줄에서 백킹 배열의 초기 크기를 지정하는 데만 사용됩니다. 100의 선택은 임의적이며, 적당히 작은 양의 정수면 충분합니다.

두 가지 생성자가 정의되어 있습니다: 기본(매개변수가 없는) 생성자는 6번 줄에 있으며, 하나의 매개변수를 받는 생성자는 10번 줄에 있습니다. 둘 다 단지 백킹 배열을 할당하며, 기본 INITIAL_CAPACITY(7번 줄) 또는 사용자가 지정한 용량(11번 줄)을 사용합니다. 제네릭 컬렉션에서 배열을 할당하는 방법에 주목하십시오:


[source,java]
----
7	elements = (E[]) new Object[INITIAL_CAPACITY];
----

Java에서는 제네릭 배열을 지원하지 않기 때문에, 이 더 간단한 접근 방식을 사용합니다:

[source,java]
----
elements = new E[INITIAL_CAPACITY];	// ERROR!
----

제네릭 배열은 Java에서 지원되지 않기 때문에, 다음과 같은 더 간단한 접근 방식은 컴파일되지 않습니다. 대신, 백킹 배열을 Object 요소의 배열로 할당한 후, 해당 배열을 (E[])로 캐스팅하여 E[] 타입의 elements 필드에 할당해야 합니다. 이러한 방법은 컴파일러 경고를 생성할 수 있지만 무시할 수 있습니다.

Stack 인터페이스에서 요구하는 다섯 가지 메서드의 구현은 비교적 간단합니다. 41번 줄의 size() 메서드는 접근자 메서드로, 단순히 size 필드의 값을 반환합니다. 14번 줄의 isEmpty() 메서드는 size 값이 0인지 여부에 따라 true 또는 false를 반환합니다.

18번 줄의 peek() 메서드는 스택이 비어 있을 경우 예외를 발생시킵니다. 그렇지 않으면 스택의 맨 위 요소인 elements[size-1]을 반환합니다.

25번 줄의 pop() 메서드는 peek() 메서드와 거의 동일하지만, 반환하기 전에 29번 줄에서 size 필드를 감소시키고 30번 줄에서 맨 위 요소를 null로 대체하여 요소를 제거합니다. 이는 접근할 수 없는 객체에 대한 참조가 남지 않도록 하기 위함입니다.

34번 줄의 push() 메서드는 본질적으로 pop() 메서드의 반대입니다. 38번 줄에서 요소를 배열의 다음 사용 가능한 위치인 elements[size]에 추가하고, 그런 다음 size 카운터를 후위 감소시킵니다.

배열이 가득 차면 size 카운터는 elements.length와 같아집니다. 이 조건이 충족될 때 push()가 호출되면, 36번 줄의 private resize() 메서드를 호출하여 배열을 두 배로 늘립니다. 이는 47번 줄에서 임시 배열 a[]를 생성하고, 48번 줄에서 모든 요소를 복사한 다음, 49번 줄에서 elements 필드에 할당합니다.

46번 줄에서 assert 문을 사용하는 것에 주목하세요. 만약 size == elements.length 조건이 충족되지 않으면, 프로그램은 오류 메시지와 함께 중단됩니다. 이는 캐치되지 않은 예외와 유사합니다. 물론, 이는 절대 발생해서는 안 되는 일입니다. resize() 메서드는 private이며, 이 클래스 내에서 호출되는 유일한 장소는 같은 조건의 if 블록 내부인 36번 줄이기 때문입니다. 여기서 assert 문을 포함한 목적은 단지 "보험" 역할을 하여, 미래의 클래스 수정으로 인해 이 조건이 참이 아닌 경우에 resize() 메서드가 잘못 호출되는 것을 방지하기 위함입니다.

예제 5.3에서 구현된 ArrayStack 클래스는 103페이지의 예제 5.1에서 Stack 클래스가 테스트되는 방식과 동일하게 테스트할 수 있습니다. push(), peek(), pop() 호출은 동일한 방식으로 작동해야 합니다. ArrayStack 클래스에는 toString() 메서드가 없기 때문에 println() 호출은 실행될 수 없습니다. 그러나 이는 적절합니다. 왜냐하면 스택은 맨 위의 요소를 제외한 다른 요소에 접근을 허용해서는 안 되기 때문입니다.

== 연결된 구현

인덱스 기반 구현의 주요 대안은 연결 리스트를 사용하는 연결된 구현입니다. (3장 참조.)


=== EXAMPLE 5.4 A LinkedStack Implementation

[source,java]
----
1	public class LinkedStack<E> implements Stack<E> {
2	    private Node<E> head = new Node<E>(); // dummy node
3	    private int size;
4
5	    public boolean isEmpty() {
6	        return (size == 0);
7	    }
8
9	    public E peek() {
10	        if (size == 0) {
11	            throw new java.util.EmptyStackException();
12	        }
13	        return head.prev.element; // top of stack
14	    }
15
16	    public E pop() {
17	        if (size == 0) {
18	            throw new java.util.EmptyStackException();
19	        }
20	        E element = head.prev.element;
21	        head.prev = head.prev.prev;
22	        head.prev.next = head;
23	        --size;
24	        return element;
25	    }
26
27	    public void push(E element) {
28	        head.prev = head.prev.next = new Node<E>(element, head.prev, head);
29	        ++size;
30	    }
31
32	    public int size() {
33	        return size;
34	    }
35
36	    private static class Node<E> {
37	        E element;
38	        Node<E> prev;
39	        Node<E> next;
40
41	        Node() {
42	            this.prev = this.next = this;
43	        }
44
45	        Node(E element, Node<E> prev, Node<E> next) {
46	            this.element = element;
47	            this.prev = prev;
48	            this.next = next;
49	        }
50	    }
51	}
----

이 클래스는 36-50번 줄에 정의된 private inner Node 클래스를 사용하여 이중 연결 리스트를 구현합니다. 각 노드는 요소 필드와 두 개의 링크 필드를 포함합니다: 하나는 리스트의 이전 노드를 가리키고, 다른 하나는 다음 노드를 가리킵니다. 41번 줄에 정의된 생성자는 null 요소와 두 링크 모두 자기 자신을 가리키는 더미 노드를 생성합니다. 45번 줄에 정의된 세 개의 인자를 받는 생성자는 세 개의 필드를 모두 초기화할 수 있게 합니다.

LinkedStack 클래스는 2-3번 줄에 두 개의 필드를 정의합니다: 헤드 노드 링크와 크기 카운터입니다. 이 구현은 prev와 next 링크가 자기 자신을 가리키는 단일 더미 노드로 빈 스택을 구현합니다. 자기 참조 포인터의 장점은 널 포인터를 피할 수 있어 push()와 pop() 메서드에서 특별한 경우를 없애줍니다.

스택이 비어 있지 않을 때, 맨 위의 요소는 항상 head.prev 링크가 참조하는 노드에 있습니다. 따라서, peek()와 pop()은 모두 head.prev.element를 반환합니다.

맨 위의 요소를 제거하려면, pop() 메서드는 이를 포함하는 노드를 삭제합니다. 이는 21-22번 줄에서 두 개의 포인터를 재설정하여 수행됩니다:

[source,java]
----
21	head.prev = head.prev.prev;
22	head.prev.prev.next = head;
----

push() 메서드는 28번 줄에서 지정된 요소를 포함하는 새로운 노드를 생성한 후, head.prev.next와 head.prev 링크를 모두 해당 노드를 가리키도록 재설정합니다. 체인 할당은 오른쪽에서 왼쪽으로 작동하여, 먼저 새로운 노드 참조를 head.prev.next에 할당한 다음, head.prev에 할당합니다. 이 연산 순서는 중요합니다. 왜냐하면 head.prev가 변경된 후에는 기존의 head.prev.next 노드에 접근할 수 없기 때문입니다.

== 공통 코드 추상화

Stack 인터페이스의 ArrayStack 및 LinkedStack 구현은 상당히 다릅니다. 그럼에도 불구하고 동일한 코드가 일부 존재합니다. size() 메서드와 isEmpty() 메서드는 동일합니다. 이들의 구현은 백킹 구조가 인덱스 기반인지 링크 기반인지에 의존하지 않습니다.

구현의 일부가 기본 데이터 구조와 독립적일 때, 이러한 부분을 추상 클래스에서 별도로 구현하는 것이 유리합니다.

=== 예제 5.5 추상 스택 클래스


[source,java]
----
1	public abstract class AbstractStack<E> implements Stack<E> {
2	    protected int size;
3
4	    public boolean isEmpty() {
5	        return (size == 0);
6	    }
7
8	    abstract public E peek();
9
10	    abstract public E pop();
11
12	    abstract public void push(E element);
13
14	    public int size() {
15	        return size;
16	    }
17	}
----

백킹 구조에 따라 의존하는 세 가지 메서드는 추상으로 선언됩니다 (8, 10, 12번 줄). 이는 물론 클래스 자체를 추상으로 선언해야 합니다.

2번 줄에서 size 필드가 private 대신 protected로 선언되어 있어야 하는데, 이는 확장된 구상 클래스에서 접근할 수 있도록 하기 위함입니다.

예제 5.5에 표시된대로 AbstractStack 클래스가 구현되었으므로, 이제 예제 5.3(104페이지) 및 예제 5.4(106페이지)의 두 구체적인 구현을 간소화할 수 있습니다. 각 클래스 헤더에 extends AbstractStack<E> 표현식을 추가하고, 그런 다음 isEmpty() 및 size() 메서드와 size 필드의 선언을 제거하면 됩니다. 이는 물론 JCF에서 사용하는 전략입니다. (70페이지의 그림 4.1을 참조하십시오.)

== 응용: RPN 계산기

스택 데이터 구조는 가장 간단한 구조 중 하나이지만, 특정 중요한 응용 분야에서 필수적입니다. 이러한 일부는 다음 예제에서 설명됩니다.

산술 식이 _후위 표기법_ (역 _폴란드 표기법_, 또는 RPN이라고도 함)에 있다고 합니다. 이는 각 연산자가 피연산자 뒤에 배치되는 경우입니다. 예를 들어, 3*(4 + 5)의 후위 표기법은 3 4 5 + *입니다. [식 3*(4 + 5)는 _중위 표기법_이라고 합니다.] 후위 표기법은 중위 표기법보다 기계에서 처리하기 쉽습니다. 후위 표기법을 처리하는 계산기를 _RPN 계산기_라고 합니다.

=== 예제 5.6 RPN 계산기

이 프로그램은 후위 표기법 식을 구문 분석하여 지정된 산술을 수행합니다. 피연산자를 누적하기 위해 스택을 사용합니다.


[source,java]
----
1	public class Calculator {
2	    public static void main(String[] args) {
3	        Deque<String> stack = new ArrayDeque<String>();
4	        Scanner in = new Scanner(System.in);
5	        while (true) {
6	            String input = in.nextLine();
7	            char ch = input.charAt(0);
8	            if (ch == '+' || ch == '-' || ch == '*' || ch == '/') {
9	                double y = Double.parseDouble(stack.pop());
10	                double x = Double.parseDouble(stack.pop());
11	                double z = 0;
12	                switch	(ch)	{
13	                    case	'+':	z = x +	y; break;
14	                    case	'-':	z = x -	y; break;
15	                    case	'*':	z = x *	y; break;
16	                    case	'/':	z = x /	y;
17	                }
18	                System.out.printf("\t%.2f %c %.2f = %.2f%n", x, ch, y, z);
19	                stack.push(new Double(z).toString());
20	            } else if (ch == 'q' || ch == 'Q') {
21	                return;
22	            } else {
23	                stack.push(input);
24	            }
25	        }
26	    }
27	}
----

Here is one run:

[source,console]
----
3
4
5
+
4.00 + 5.00 = 9.00
*
3.00 * 9.00 = 27.00
10
/
27.00 / 10.00 = 2.70
1 –
2.70 – 1.00 = 1.70
Q
----

3번 줄에서 프로그램은 예제 5.1(103페이지)의 것과 같은 문자열 스택을 인스턴스화합니다. 그런 다음 5번 줄에서 무한 while 루프에 들어가며, 각 반복마다 상호 작용적으로 문자열을 읽습니다(6번 줄).

사용자가 +, -, *, /, q 또는 Q 이외의 입력을 하면, 프로그램은 숫자로 간주하고 해당 숫자를 스택에 푸시합니다(23번 줄). 이 연산자 중 하나인 경우, 최상위 두 숫자가 스택에서 팝되고(9-10번 줄), 해당 숫자에 대해 연산이 적용됩니다. 결과가 출력되고(18번 줄), 스택에 푸시됩니다(19번 줄).

사용자가 q 또는 Q(“quit”의 약자)를 입력하면 프로그램이 종료됩니다.

인간 독자들은 산술 표현식에 대해 후위 표기법보다 중위 표기법을 선호합니다. 다음 예제는 주어진 중위 표현식을 후위 표현식으로 변환합니다.

=== 예제 5.7 중위 표현식을 후위 표현식으로 변환하기


[source,java]
----
1	public class TestScanner {
2	    public static void main(String[] args) {
3	        Deque<String> stack = new ArrayDeque<String>();
4	        String line = new Scanner(System.in).nextLine();
5	        System.out.println(line);
6	        Scanner scanner = new Scanner(line);
7	        while (scanner.hasNext()) {
8	            if (scanner.hasNextInt()) {
9	                System.out.print(scanner.nextInt() + " ");
10	            } else {
11	                String str = scanner. next();
12	                if ("+-*/".indexOf(str) >= 0) {
13	                    stack.push(str);
14	                } else if (str.equals(")")) {
15	                    System.out.print(stack.pop() + " ");
16	                }
17	            }
18	        }
19	        while (!stack.isEmpty()) {
20	            System.out.print(stack.pop() + " ");
21	        }
22	        System.out.println();
23	    }
24	}
----

The output is:

[source,java]
----
( 80 - 30 ) * ( 40 + 50 / 10 )
80 30 - 40 50 10 / + *
----

출력 결과는 프로그램이 중위 표현식 ( 80 - 30 )*( 40 + 50 / 10 )을 후위 표현식인 80 30 - 40 50 10 / + *으로 변환했음을 보여줍니다.

프로그램은 스택을 사용합니다. 이는 라인 3에서 선언되고, 스캐너는 라인 6에서 선언됩니다. 스캐너는 입력 라인에서 정수와 문자열 토큰을 추출합니다. 토큰이 정수인 경우 라인 9에서 즉시 출력됩니다. 그것이 "+", "-", "*", "/" 중 하나인 경우 라인 13에서 스택에 푸시됩니다. 만약 그것이 ")" 문자열이라면, 스택의 맨 위 요소가 팝되고 라인 15에서 출력됩니다. 입력 라인이 완전히 구문 분석된 후, 남은 요소들은 라인 19-21에서 스택에서 팝되어 출력됩니다.

== 리뷰 질문

1. 스택이 LIFO 구조라고 불리는 이유는 무엇인가요?
2. 스택을 다음과 같이 부르는 것이 합리적일까요?
a. LILO 구조?
b. FILO 구조?
3. 다음에 대한 설명은 무엇인가요?
a. Prefix 표기법?
b. Infix 표기법?
c. Postfix 표기법?
4. 후위 표현식에 대해 각각 다음이 사실인지 결정하세요:
a. x y + z + = x y z + +
b. x y + z - = x y z - +
c. x y - z + = x y z + -
d. x y - z - = x y z - -



