= 큐

큐는 먼저 들어온 것이 먼저 나가는 (FIFO) 프로토콜을 구현한 컬렉션입니다. 이는 컬렉션에서 접근 가능한 유일한 객체가 삽입된 첫 번째 객체인 것을 의미합니다. 대표적인 큐의 예는 대기 줄입니다.

== 큐의 연산

큐의 기본 연산은 다음과 같습니다:

1. 큐 뒤쪽에 요소를 추가합니다.
2. 큐의 현재 맨 앞 요소에 액세스합니다.
3. 큐의 현재 맨 앞 요소를 제거합니다.

일부 저자들은 추가 및 제거 연산에 대해 enqueue와 dequeue 용어를 사용합니다.

== JCF Queue 인터페이스

페이지 70의 그림 4.1에 나와 있는 것처럼, Java Collections Framework에는 네 가지 클래스에서 구현된 Queue 인터페이스가 포함되어 있습니다: LinkedList 클래스, AbstractQueue 클래스, PriorityQueue 클래스 및 ArrayDeque 클래스. 간단한 FIFO 큐의 경우, ArrayDeque 클래스가 가장 적합합니다.

[source,java]
----
Queue<String> queue = new ArrayDeque<String>();
----

이는 큐의 모든 일반적인 기능을 제공합니다. (페이지 91을 참조하세요.)

=== 예제 6.1 문자열 큐 테스트


[source,java]
----
1	public class TestStringStack {
2	    public static void main(String[] args) {
3	        Queue<String> queue = new ArrayDeque<String>();
4	        queue.add("GB");
5	        queue.add("DE");
6	        queue.add("FR");
7	        queue.add("ES");
8	        System.out.println(queue);
9	        System.out.println("queue.element(): " + queue.element());
10	        System.out.println("queue.remove(): " + queue.remove());
11	        System.out.println(queue);
12	        System.out.println("queue.remove(): " + queue.remove());
13	        System.out.println(queue);
14	        System.out.println("queue.add(\"IE\"): ");
15	        queue.add("IE");
16		    System.out.println(queue);
17		    System.out.println("queue.remove(): " + queue.remove());
18		    System.out.println(queue);
19	    }
20	}
----

The output is:

[source,java]
----
[GB, DE, FR, ES]
queue.element(): GB
queue.remove(): GB
[DE, FR, ES]
queue.remove(): DE
[FR, ES]
queue.add("IE"):
[FR, ES, IE]
queue.remove(): FR
[ES, IE]
----

add, element 및 remove 연산은 각각 라인 4, 9 및 10에서 설명되었습니다.

예제 6.1의 출력과 페이지 103의 예제 5.1의 출력을 비교하면, 큐와 스택의 유일한 작업상의 차이점은 액세스 지점입니다. 큐의 경우, 이것은 가장 "오래된" 요소인 가장 앞쪽에 위치합니다. 스택의 경우, 가장 "최근에 도착한" 요소가 가장 위에 위치합니다.

ArrayDeque 클래스의 경우, toString() 메서드 (라인 8에서 println() 메서드에 의해 자동으로 호출됨)는 큐를 앞에서 뒤로, 스택을 위에서 아래로 표시합니다. 따라서 두 경우 모두 액세스 지점이 표시의 왼쪽 끝에 있습니다.

== 간단한 Queue 인터페이스

큐의 작업 요구 사항은 이 간단한 자바 인터페이스로 정형화될 수 있습니다:

=== 예제 6.2 Queue 인터페이스

[source,java]
----
1	public interface Queue<E> {
2	    public void add(E element);
3	    public E element();
4	    public boolean isEmpty();
5	    public E remove();
6	    public int size();
7	}
----

이 인터페이스는 세 가지 필수 큐 작업 외에도 isEmpty() 메서드와 size() 메서드를 지정합니다.

예제 6.2에 나와 있는 Queue 인터페이스를 페이지 89의 그림 4.10에 나와 있는 JCF의 Queue 인터페이스와 비교해 보세요. JCF의 Queue 인터페이스는 offer(), peek(), poll() 메서드를 포함하고 있습니다. 대부분의 상황에서, 이들은 각각 add(), element(), remove() 메서드와 동일한 작업입니다. 한정된 용량의 큐가 가득 찬 경우, add() 메서드는 IllegalStateException을 던지지만, offer() 메서드는 단순히 false를 반환합니다. 큐가 비어 있는 경우, element() 및 remove() 메서드는 NoSuchElementException을 던지지만, peek() 및 poll() 메서드는 단순히 null을 반환합니다.


== 색인 구현

스택 및 다른 선형 데이터 구조와 마찬가지로 큐는 보통 배열을 사용하여 구현할 수 있습니다. 예제 6.3에 나와 있는 ArrayQueue 클래스는 페이지 104의 예제 5.3에 나와 있는 ArrayStack 클래스와 유사합니다.


[source,java]
----
1	public class ArrayQueue<E> implements Queue<E> {
2	    private E[] elements;
3	    private int front;
4	    private int back;
5	    private static final int INITIAL_CAPACITY = 4;
6
7	    public ArrayQueue() {
8	        elements = (E[]) new Object[INITIAL_CAPACITY];
9	    }
10
11	    public ArrayQueue(int capacity) {
12	        elements = (E[]) new Object[capacity];
13	    }
14
15	    public void add(E element) {
16	        if (size() == elements.length - 1) {
17	            resize();
18	        }
19	        elements[back] = element;
20	        if (back < elements.length - 1) {
21	            ++back;
22	        } else {
23	            back = 0; //wrap
24	        }
25	    }
26
27	    public E element() {
28	        if (size() == 0) {
29	            throw new java.util.NoSuchElementException();
30	        }
31	        return elements[front];
32	    }
33
34	    public boolean isEmpty() {
35	        return (size() == 0);
36	    }
37
38	    public E remove() {
39	        if (size() == 0) {
40	            throw new java.util.NoSuchElementException();
41	        }
42	        E element = elements[front];
43	        elements[front] = null;
44	        ++front;
45	        if (front == back) { // queue is empty
46	            front = back = 0;
47	        }
48	        if (front == elements.length) { // wrap
49	            front = 0;
50	        }
51	        return element;
52	    }
53
54	    public int size() {
55	        if (front <= back) {
56	            return back - front;
57	        } else {
58	            return back - front + elements.length;
59	        }
60	    }
61
62	    private void resize() {
63	        int size = size();
64	        int len = elements.length;
65	        assert size == len;
66	        Object[] a = new Object[2*len];
67	        System.arraycopy(elements, front, a, 0, len - front);
68	        System.arraycopy(elements, 0, a, len - front, back);
69	        elements = (E[])a;
70	        front = 0;
71	        back = size;
72	    }
73	}
----

이 구현은 크기 카운터를 저장하는 대신 배열에 대한 앞쪽과 뒷쪽 인덱스를 저장합니다. 큐의 앞 요소는 항상 elements[front]에 있으며, 큐의 뒷 요소는 항상 elements[back-1]에 있습니다 (back = 0일 때를 제외하고). 앞 인덱스는 큐에서 요소가 제거될 때마다 진행됩니다 (라인 44에서), 그리고 뒷 인덱스는 요소가 추가될 때마다 진행됩니다 (라인 21에서). 두 경우 모두, 인덱스가 배열의 끝에 도달하면 0으로 "진행"됩니다. 이는 큐를 배열의 끝을 "감싸는" 것처럼 만들어주어, 배열 요소를 재사용할 수 있도록 합니다.

== 색인 구현

우리는 이전에 페이지 106의 예제 5.4에서 스택 인터페이스를 구현한 것과 같은 방식으로 이를 사용하여 이중 연결 리스트를 사용하여 큐 인터페이스를 구현할 수 있습니다.

=== 예제 6.4 LinkedQueue 클래스


[source,java]
----
1	public class LinkedQueue<E> implements Queue<E> {
2	    private Node<E> head = new Node<E>(); // dummy node
3	    private int size;
4
5	    public void add(E element) {
6	        head.prev = head.prev.next = new Node<E>(element, head.prev, head);
7	        ++size;
8	    }
9
10	    public E element() {
11	        if (size == 0) {
12	            throw new java.util.EmptyStackException();
13	        }
14	        return head.next.element; // front of queue // next <--> prev
15	    }
16
17	    public boolean isEmpty() {
18	        return (size == 0);
19	    }
20
21	    public E remove() {
22	        if (size == 0) {
23	            throw new java.util.EmptyStackException();
24	        }
25	        E element =	head.next.element;	//	next	<-->	prev
26	        head.next =	head.next.next;	//	next	<-->	prev
27		    head.next.prev = head;	//	next	<-->	prev
28		    --size;
29		    return element;
30	    }
31
32		public int size() {
33		    return size;
34		}
35
36		private static class Node<E> {
37		    E element;
38		    Node<E> prev;
39		    Node<E> next;
40
41		    Node() {
42		        this.prev = this.next = this;
43		    }
44
45		    Node(E element, Node<E> prev, Node<E> next) {
46		        this.element = element;
47		        this.prev = prev;
48		        this.next = next;
49		    }
50		}
51	}
----

LinkedStack 클래스에 필요한 변경 사항은 메서드 이름 이외에는 라인 14 및 25-27에서만 이루어집니다. 여기서는 next와 prev 필드를 교환해야 합니다.

== 응용 프로그램: 클라이언트-서버 시스템

큐는 FIFO 프로토콜을 구현하는 데 사용됩니다. 이는 클라이언트-서버 응용 프로그램에서 흔합니다. 예를 들어, 요금 도로의 자동차가 요금 징수소에 도착할 때, 자동차는 클라이언트이고, 요금 징수소는 서버입니다. 자동차가 요금 징수소를 통과하는 속도가 도착 속도보다 느리면 대기 줄이 형성됩니다. 그것이 큐입니다.

=== 예제 6.5 클라이언트-서버 시뮬레이션

이 시뮬레이션은 객체 지향 프로그래밍 (OOP)을 보여줍니다. Java 객체는 모든 상호 작용하는 클라이언트와 서버를 나타내기 위해 인스턴스화됩니다. 이를 위해 먼저 Client 및 Server 클래스를 정의합니다.

이는 이벤트 기반 시뮬레이션으로, 클라이언트는 무작위 시간에 서비스를 받기 위해 도착하고, 서비스는 무작위 기간 동안 수행됩니다. 각 클라이언트는 도착 시간, 서비스 시작 시간 및 종료 시간을 가집니다. 모든 시간 값은 정수입니다.

[source,java]
----
1	public class Client {
2	    private int id;
3	    private int startTime;
4
5	    public Client(int id, int time) {
6	        this.id = id;
7	        System.out.printf("%s arrived at time %d.%n", this, time);
8	    }
9
10	    public void setStartTime(int time) {
11	        startTime = time;
12	    }
13
14	    public String toString() {
15	        return "#" + id;
16	    }
17	}
----

시뮬레이션을 추적하기 위해, Client 생성자는 도착 시간을 출력합니다 (라인 7에서).

각 서버는 한 번에 최대 하나의 클라이언트를 제공하므로, Server 클래스에는 해당 서버의 클라이언트를 참조하는 client 필드가 있습니다. 또는 서버가 대기 상태인 경우 null입니다.

각 Server 객체는 또한 현재 클라이언트에 대한 서비스를 중지할 시간을 저장합니다. 이 시간은 해당 클라이언트에 대한 서비스를 시작한 시간에 서비스 시간(양의 난수)을 추가하여 계산됩니다. 이러한 서비스 시간을 생성하는 데 사용되는 난수 생성기는 Server 객체의 random 필드에 저장됩니다. 서버의 실제 서비스 시간은 각 클라이언트마다 다릅니다. 그러나 서버의 평균 서비스 시간은 서버가 생성될 때 초기화되는 서버의 고정 속성입니다 (라인 10에서):

[source,java]
----
1	public class Server {
2	    private Client client;
3	    private int id;
4	    private int stopTime = -1;
5	    private double meanServiceTime;
6	    private ExpRandom random;
7
8	    public Server(int id, double meanServiceTime) {
9	        this.id = id;
10	        this.meanServiceTime = meanServiceTime;
11	        this.random = new ExpRandom(meanServiceTime);
12	    }
13
14	    public double getMeanServiceTime() {
15	        return meanServiceTime;
16	    }
17
18	    public int getStopTime() {
19	        return stopTime;
20	    }
21
22	    public boolean isIdle() {
23	        return client == null;
24	    }
25
26	    public void startServing(Client client, int time)	{
27	        this.client = client;
28	        this.client.setStartTime(time);
29	        this.stopTime = time + random.nextInt();
30	        System.out.printf("%s started serving client %s	at time %d.%n",
31	                this, client, time);
32	    }
33
34	    public void stopServing(int time) {
35	        System.out.printf("%s stopped serving client %s at time %d.%n",
36	                this, client, time);
37	        client = null;
38	    }
39
40	    public String toString() {
41	        return "Server " + "ABCDEFGHIJKLMNOPQRSTUVWXYZ".charAt(id);
42	    }
43	}
----

startServing() 메서드 (라인 26-32)는 서버에 새로운 클라이언트를 할당하고, 시작 시간을 Client 객체에 저장하고, 서버 자체의 stopTime 필드에 중지 시간을 계산하여 저장하고, 이러한 작업에 대한 보고서를 출력합니다. stopServing() 메서드 (라인 34-38)는 중지 시간을 Client 객체에 저장하고 다른 보고서를 출력합니다.

시뮬레이션이 현실적이 되려면 실제 세계의 자연스러운 불확실성을 시뮬레이션하기 위해 무작위 생성된 숫자를 사용해야 합니다. 이러한 무작위 숫자는 표현하는 자연스러운 불확실성과 동일한 분포를 가져야 합니다. 서비스 시간과 클라이언트 도착 간의 시간은 모두 지수적으로 분포되는 경향이 있습니다. 이는 시간 t가 숫자 x보다 작을 확률이 stem:[p = 1 - e^{- \lambda x}]임을 의미합니다.

그러나 Math.random() 메서드는 범위 stem:[0 \le p \lt 1]에서 균일하게 분포된 숫자를 반환합니다. 따라서 지수적으로 분포된 무작위 변수 x로 무작위 숫자 p를 변환하려면, stem:[x = -(1/\lambda) \ln(1 – p)] 방정식을 해결하여 얻습니다. 상수 stem:[1/\lambda]는 분포의 평균입니다. 따라서 nextDouble() 메서드를 라인 9에 표시된대로 작성합니다:

[source,java]
----
1	public class ExpRandom extends java.util.Random {
2	    private double mean;
3
4	    public ExpRandom(double mean) {
5	        this.mean = mean;
6	    }
7
8	    public double nextDouble() {
9	        return -mean*Math.log(1 - Math.random());
10	    }
11
12	    public int nextInt() {
13	        return (int)Math.ceil(nextDouble());
14	    }
15	}
----

아래에 표시된 main 클래스에 의해 실제 시뮬레이션이 수행됩니다. 라인 2-5에서 시뮬레이션을 위해 네 가지 상수를 설정합니다: 서버의 수, 서비스를 받으러 온 클라이언트의 수, 서버들 사이의 평균 서비스 시간, 그리고 클라이언트들의 도착 간의 평균 시간입니다.

큐는 서비스를 받으러 온 클라이언트를 보관하고 비어있는 서버를 기다리는 대기열입니다. 시뮬레이션은 두 개의 무작위 지수 분포 숫자 생성기를 인스턴스화하고 (라인 7-8), 서버 및 클라이언트 객체에 대한 별도의 배열을 생성합니다 (라인 9-10):


[source,java]
----
1	public class Simulation {
2	    private static final int SERVERS = 3;
3	    private static final int CLIENTS = 20;
4	    private static final double MEAN_SERVICE_TIME = 25;
5	    private static final double MEAN_ARRIVAL_TIME = 4;
6	    private static Queue<Client> queue = new ArrayDeque<Client>();
7	    private static ExpRandom randomService = new ExpRandom(MEAN_SERVICE_TIME);
8	    private static ExpRandom randomArrival = new ExpRandom(MEAN_ARRIVAL_TIME);
9	    private static Server[] servers = new Server[SERVERS];
10	    private static Client[] clients = new Client[CLIENTS];
11
12		public Simulation() {
13		    String fmt = "%-27s %6d%n";
14		    System.out.printf(fmt, "Number of servers:", SERVERS);
15		    System.out.printf(fmt, "Number of clients:", CLIENTS);
16		    System.out.printf(fmt, "Mean service time:", MEAN_SERVICE_TIME);
17		    System.out.printf(fmt, "Mean interarrival time:", MEAN_ARRIVAL_TIME);
18		    for (int i=0; i<SERVERS; i++) {
19		        double meanServiceTime = randomService.nextDouble();
20		        servers[i] = new Server(i, meanServiceTime);
21		        System.out.printf("Mean service time for %s: %4.1f%n",
22		        servers[i], servers[i].getMeanServiceTime());
23		    }
24		    int nextArrivalTime = 0;
25		    for (int t=0, clientId=0; clientId < CLIENTS; t++) {
26		        if (t == nextArrivalTime) {
27		            nextArrivalTime = t + randomArrival.nextInt();
28		            Client client = clients[clientId] = new Client(++clientId, t);
29		            queue.add(client);
30		            System.out.println("\tClient queue: " + queue);
31		        }
32		        for (Server server : servers) {
33		            if (t == server.getStopTime()) {
34		                server.stopServing(t);
35		            }
36		            if (server.isIdle() && !queue.isEmpty()) {
37		                Client client = (Client)queue.remove();
38		                System.out.println("\tClient queue: " + queue);
39		                server.startServing(client,t);
40		            }
41		        }
42		    }
43		}
44
45		public static void main(String[] args) {
46		    new Simulation();
47		}
48	}
----


The output for one run was:

[source,console]
----
Number of servers:	3
Number of clients:	12
Mean service time:	25
Mean interarrival time:	4
Mean service time for Server A: 17.2
Mean service time for Server B: 51.7
Mean service time for Server C: 24.5
#1 arrived at time 0.
        Client queue: [#1]
        Client queue: []
Server A started serving client #1 at time 0. #2 arrived at time 2.
        Client queue: [#2]
        Client queue: []
Server B started serving client #2 at time 2. #3 arrived at time 4.
        Client queue: [#3]
        Client queue: []
Server C started serving client #3 at time 4. #4 arrived at time 6.
        Client queue: [#4]
#5 arrived at time 7.
        Client queue: [#4, #5]
#6 arrived at time 11.
        Client queue: [#4, #5, #6]
Server A stopped serving client #1 at time 11.
        Client queue: [#5, #6]
Server A started serving client #4	at time	11.
#7 arrived at time 12.
        Client queue: [#5, #6, #7]
#8 arrived at time 16.
        Client queue: [#5, #6, #7,	#8]
#9 arrived at time 23.
        Client queue: [#5, #6, #7,	#8, #9]
#10 arrived at time 30.
        Client queue: [#5, #6, #7,	#8, #9,	#10]
Server C stopped serving client #3	at time	30.
        Client queue: [#6, #7, #8,	#9, #10]
Server C started serving client #5	at time	30.
Server B stopped serving client #2	at time	33.
        Client queue: [#7, #8, #9,	#10]
Server B started serving client #6	at time	33.
#11 arrived at time 34.
        Client queue: [#7, #8, #9, #10, #11]
#12 arrived at time 36.
        Client queue: [#7, #8, #9, #10, #11, #12]
----

시뮬레이션의 주된 루프는 라인 25-42에 있습니다. 시계 틱 t마다 한 번 반복되며, 모든 클라이언트가 도착할 때까지 계속됩니다. 새로운 클라이언트가 도착해야 할 시간이면, 라인 27-30이 실행되어 다음 도착 시간을 설정하고, 새로운 클라이언트 객체를 생성하고, 새 클라이언트를 큐에 추가합니다. 그런 다음 라인 32-41에서 각 Server 객체가 업데이트됩니다. 활성 서버가 클라이언트를 서비스하는 것을 마쳤을 때인 경우, 그것의 stopServing() 메서드가 호출됩니다. 서버가 대기 상태이고 큐에 대기 중인 클라이언트가 있다면, 큐에서 다음 클라이언트가 제거되고 해당 서버가 서비스를 시작합니다.

출력은 한 번의 실행 진행 상황을 보여줍니다. 클라이언트 #4가 큐에서 대기해야 하는 첫 번째 클라이언트이며, 그 후로 #5와 #6이 따릅니다. t = 11에 서버 A가 클라이언트 #1의 서비스를 마치고 클라이언트 #4를 서비스하기 시작하므로, 그때 클라이언트 #4가 큐를 떠납니다.

다음 서버(Server C)가 비어있는 시간인 t = 30에는 더 네 명의 클라이언트가 도착하여 큐에서 대기하고 있습니다. 그런 다음 C는 #5를 서비스하기 시작합니다. t = 33에 서버 B가 #2의 서비스를 마치고 #6을 서비스하기 시작합니다. 그러면 시뮬레이션이 t = 36에서 끝날 때 큐가 다시 여섯 명의 대기 클라이언트로 성장합니다.

예제 6.5의 시뮬레이션은 주로 시계의 한 번의 틱마다 주된 루프가 반복되므로 _시간 기반 시뮬레이션_이라고 합니다. 반면에 이벤트 기반 시뮬레이션은 주된 루프가 각 이벤트마다 한 번씩 반복되는 것입니다: 작업 도착, 서비스 시작 또는 서비스 종료. 이벤트 기반 시뮬레이션은 보통 더 간단하지만, 모든 서버가 동일한 속도로 작동해야 합니다.

== 리뷰 질문

1. 큐가 FIFO 구조로 불리는 이유는 무엇인가요?
2. 큐를 다음과 같이 부르는 것이 의미가 있을까요?
a. LILO 구조?
b. FILO 구조?
3. 연속적인 구현에 비해 연결 구현의 큐의 장단점은 무엇인가요?
